### ISSUE TITLE
appcompatparser - dedupe appcompat output

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#101]
if an item is in both control sets then dedupe accordingly
maybe the control set column can say "1,2"?

**Comment by EricZimmerman** [comment]
this would break sorting by int.

i would also have to take last modified into account, so it would be a combo of the timestamp + full path.

maybe i can add a --dd switch to dedupe?

**Comment by EricZimmerman** [comment]
handling in issue 107

https://github.com/EricZimmerman/Issues/issues/107
