### ISSUE TITLE
TLE -f/-d option

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#104]
auto open whatever is provided to -f or -d
(added timelineexplorer to my path, would save me a couple clicks :))

**Comment by EricZimmerman** [comment]
i dont know what you mean

you can already do an Open With and it works

its done this forever. if you drop a file on the program it works too.

where are you getting -f or -d from? 

i did just add the ability to give it a directory and it will find files in the directory (not recursive) and load them. recursive could be messy!

**Comment by EricZimmerman** [comment]
just pushed an update. try it out for a file or directory (open with or dropping it)

test and reopen if need be
