### ISSUE TITLE
Import issue Timeline explorer

### ISSUE THREAD

**Issue by DfirJos** [EricZimmerman/Issues#108]
Loving your tool for timeline analysis! It works perfect for most CSV's that I imported. Unfortunately it did not succesfully parse a CSV that was generated by MFTECmd: 

![image](https://user-images.githubusercontent.com/11965973/66267163-7aaf2280-e84b-11e9-9cad-798b55591d2c.png)

The file I tried to import is:

[20191006053121_MFTECmd_$J_Output_snippet.txt](https://github.com/EricZimmerman/Issues/files/3694161/20191006053121_MFTECmd_.J_Output_snippet.txt) (I renamed the extension due to Github not being able to upload csv's.)

Note that for a different export from $J with MFTECmd everything parses perfectly. I used all the latest version of MFTECmd and Timeline (0.4.4.6 and 0.9.4.1).

Any idea what is going wrong here?

**Comment by EricZimmerman** [comment]
looking now

**Comment by EricZimmerman** [comment]
At some point, source file was added to the output. 

i am updating TLE to handle this case now.

check for updates and things should work

**Comment by DfirJos** [comment]
Thanks Eric. I Highly appreciate your quick response and solving it so fast!
