### ISSUE TITLE
TLE - Ctrl+t to tag a row throws an error

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#111]
v0.9.4.1
Press ctrl t throws an error message and doesn't tag the row (also doesnt crash conveniently)

**Comment by EricZimmerman** [comment]
What file are you using?

**Comment by randomaccess3** [comment]
ive used output from recmd and evtxecmd so far

**Comment by EricZimmerman** [comment]
in the files that cause the crash, do you see a TAG or LINE # column? if not, thats the problem. ill fix it either way, but let me know

**Comment by EricZimmerman** [comment]
This is fixed. will be in next update

**Comment by EricZimmerman** [comment]
its up
