### ISSUE TITLE
TimelineExplorer - Format Cells

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#112]
option to change the format character to allow for easier review.
For ex:
Being able to replace the , with a \n in PECmd output of files loaded

**Comment by EricZimmerman** [comment]
like this? the selected delimiter will be replaced with \r\n

![image](https://user-images.githubusercontent.com/4265254/67725597-4dbcde00-f9b9-11e9-9855-be750f0a79ce.png)

**Comment by EricZimmerman** [comment]
this will be in next release
