### ISSUE TITLE
RegistryExplorer: SAM Hive displaying Unicode characters instead of 'data'

### ISSUE THREAD

**Issue by Fetchered** [EricZimmerman/Issues#113]
Occurs in RE 1.4.3.0, 1.5.1.1 and 1.5.2.0. Load SAM hive (Win 7 and Win 10) and browse to SAM\Domains\Account\Aliases\Members\<SID>\<RID>. Data column displays properly when RID 03E8 is selected (showing 4-byte hex RID's for the groups to which a member belongs), but every other user hex RID selected displays the 4-byte hex RID's for the groups under the Data column as Unicode characters instead of the actual hex data displayed.

Screenshots attached. Can send SAM hive if required.

![Unicode-Output5-NEW](https://user-images.githubusercontent.com/10457978/68261566-73d92280-0038-11ea-9ea0-f9887dedb9a5.PNG)
![Unicode-Output1-NEW](https://user-images.githubusercontent.com/10457978/68261567-73d92280-0038-11ea-85f2-cfd24695eab0.PNG)
![Unicode-Output2-NEW](https://user-images.githubusercontent.com/10457978/68261568-73d92280-0038-11ea-8ec2-755688ba680b.PNG)
![Unicode-Output3-NEW](https://user-images.githubusercontent.com/10457978/68261569-73d92280-0038-11ea-96cd-349fee6587ea.PNG)
![Unicode-Output4-NEW](https://user-images.githubusercontent.com/10457978/68261570-73d92280-0038-11ea-95e7-1be72b09ee73.PNG)

**Comment by EricZimmerman** [comment]
not sure what you are expecting to see differently here. what is the "correct" behavior in your opinion?

if you click on the users key, what does the plugin show?

**Comment by Fetchered** [comment]
As you can see when viewing RID 03E8, the display for 'Data' shows correctly, the actual hex data for the RID. That's the only RID that shows the data correctly, the remainder show the data as if it's trying to parse the hex and present a form of readable text, vice providing the actual data contained in the field. The correct behavior should be to display the Data as the hex RID in its proper 4-byte format, as shows in the image with 03E8 selected.

The Users plugin only shows the Groups to which the user belongs which are Builtin, not any user-created groups. The images I've sent have this issue occuring in the user-RID values for  User-created groups under Domains\Account\Aliases\Members\<SID>\<RID>. I already have another issue opened to resolve that the Users plugin does not display any User-created groups on the system, only builtins.

![RegExplorer-UsersPlugin-BuiltinGroups](https://user-images.githubusercontent.com/10457978/68263147-28754300-003d-11ea-8925-375b71d502e1.PNG)

**Comment by EricZimmerman** [comment]
ill need the hive(s) to look at this closer.

what does the technical details report for the incorrect keys look like? what does the hex viewer show for those keys?

if the value type falls outside a range of values it is going to be considered RegUnknown

**Comment by EricZimmerman** [comment]
i can see the sid in the raw data bytes, so the hex view should contain those same bytes. for whatever reason, the type of the value is not stored as regbinary in every case, which is leading to it trying to be interpreted as unicode, etc. it appears to be getting the bytes correct, but the value type is wrong (for whatever reason). you can compare the data in tech details for each key to see the exact offset for the value type after selecting the value in question, then the property for the type

**Comment by Fetchered** [comment]
I'll send the hive, and start poking around the tech details. Attached as SAM.txt.
[SAM.txt](https://github.com/EricZimmerman/Issues/files/3812292/SAM.txt)

**Comment by EricZimmerman** [comment]
you are under the aliases key. the plugin doesnt deal with that and probably wont. another plugin would be better for that key/subkey but the mechanics of it look to work just the same as the users area. namely, the type identifies which other key somewhere else you need to look at.

if you want to explain how that works, as far as tying things together under aliases i can look to write a plugin, but this does not appear to be a bug in how RE is presenting data.

if you decide to explain how the relationships work, please open a new issue and i can take a look at writing a plugin
