### ISSUE TITLE
RegistryExplorer: SAM hive Users\Names displaying RID's as RegUnknown, no Value/RAW data

### ISSUE THREAD

**Issue by Fetchered** [EricZimmerman/Issues#114]
RE 1.4.3.0, 1.5.1.1 and 1.5.2.0, using SAM hives from Win7 and Win10 systems. When browsing to SAM\Domains\Account\Users\Names\<name>, the Data column on the right is empty, the Value and Raw value are both empty (4 bytes x 00) and the Value type displays 'RegUnknown' and displays the RID in only 3 hex characters (eg. 0x1F5 for RID 501 vice 0x01F5 or F5 01 00 00 as should exist in the Data or RAW field). Binary viewer tab also shows no value or data (4 bytes x 00)

Screenshots below, can send SAM if required.
![SAM-User-Names-RID-2](https://user-images.githubusercontent.com/10457978/68262164-560cbd00-003a-11ea-9830-09c4e3c90ff8.PNG)
![SAM-User-Names-RID-1](https://user-images.githubusercontent.com/10457978/68262165-560cbd00-003a-11ea-96cd-df2f796592d2.PNG)

**Comment by EricZimmerman** [comment]
as with the other one, what are you expecting to see here? what does the plugin show when clicking on Users key?

why do you think something is broken?

**Comment by Fetchered** [comment]
Expecting to see the Raw hex value in the Raw value field, much like with the other one under 03E8. The value type being displayed as 'RegUnknown' with data which is not a 'type' but a 'value' leaves the interpretation of the data open for questioning. No actual data appears in the fields where we expect data to appear (Value data, Raw value, Binary value), Instead, a 'value' appears in the 'value **type**' field. 

I would expect to see the RAW data for the actual HEX RID identifying how the Users _name_ is associated with the Users _RID_. The Users plugin does not display the HEX RID, only the decimal conversion.

**Comment by EricZimmerman** [comment]
thats not how it works afaik. the value under the key path you mention is just a pointer to the other value, based on its type. For whatever reason, they decided to use the value type to make this link vs value data. the stuff under Names key is linked to the stuff under users based on the Names RegType value, so you know what name goes with what User subkey.

The data you are seeing IS the value data (all 0s).

![image](https://user-images.githubusercontent.com/4265254/71906000-45aab880-3137-11ea-80b1-500e3e16bf32.png)

unless i am completely misunderstanding what you want here, i do not see the issue.

**Comment by EricZimmerman** [comment]
if you can articulate what is wrong, or what you want added to the plugin, etc i can look at that, but this does not look like an issue to be as is

**Comment by Fetchered** [comment]
Hi Eric,

I guess what I'm saying is that RegistryExplorer labels the value as
"RegUnknown". Is there an actual type called RegUnknown? If so, I don't
know what the value for RegUnknown is, so I can't say why the tool calls it
RegUnknown. If there is no actual type with that name, why not call it for
what it is (in this instance), a RID?

Also, If you look at the second photo I attached in the issue, it shows on
the Values tab that the Value Type is RegUnknown, and the Data field is
00's. Yet, the table below expands on the type field and says it's
"RegUnknown (0x3F1, 1009 decimal)". There is no indication, in that tab, of
where RE has pulled the 0x3F1 from, and there's no indication of what a
RegUnknown data type is.

The value, in your example, is 0x1F4, but RE is assuming that, for these
records, the value at offset 10 is a data type, when it's not. It's a RID
value.

Hopefully that makes sense.

**Comment by EricZimmerman** [comment]
if its not one of the known value types (RegSZ, RegBinary, etc) it gets marked as unknown. Unknown is going to display whatever the value for the value type is. I suggest exploring technical details view for some known key/values with types like binary, string, qword, etc to see what they look like.

The Value TYPE (vs data) is where that info comes from.

This will help:

https://binaryforay.blogspot.com/2015/01/registry-hive-basics-part-3-vk-records.html

 Type
The Type is found at offset 0x10 and is stored as a 32-bit unsigned integer. In our first example, the Type is 0x01000000, or 1 in decimal. There are over a dozen standard types used in the Registry, as seen below:

    RegNone = 0x0000: No type (the stored value, if any)
    RegSz = 0x0001: A string value, normally stored and exposed in UTF-16LE
    RegExpandSz = 0x0002: An 'expandable' string value that can contain environment variables, normally stored and exposed in UTF-16LE
    RegBinary = 0x0003: Binary data (any arbitrary data)
    RegDword = 0x0004: A DWORD value, a 32-bit unsigned integer (little-endian)
    RegDwordBigEndian = 0x0005: A DWORD value, a 32-bit unsigned integer (big endian)
    RegLink = 0x0006: A symbolic link (UNICODE) to another Registry key, specifying a root key and the path to the target key
    RegMultiSz = 0x0007: A multi-string value, which is an ordered list of non-empty strings, normally stored and exposed in UTF-16LE, each one terminated by a NUL character
    RegResourceList = 0x0008: A resource list (used by the Plug-n-Play hardware enumeration and configuration)
    RegFullResourceDescription = 0x0009: A resource descriptor (used by the Plug-n-Play hardware enumeration and configuration
    RegResourceRequirementsList = 0x000A: A resource requirements list (used by the Plug-n-Play hardware enumeration and configuration)
    RegQword = 0x000B: A QWORD value, a 64-bit integer (either big- or little-endian, or unspecified)
    RegFileTime = 0x0010: FILETIME data

One thing to notice is that for the RegNone Type, it says the data has no type, not that there is no data.

**Comment by Fetchered** [comment]
I can understand that. There are two issues here though. Using similar
nomenclature to identify a value at offset 10 and calling it RegUnknown
vice Unknown implies that it is inherently named that by Microsoft. You
chose the name RegUnknown, but provided no clarity that it was your choice
to using a similar naming format, not that Microsoft named it that. This
makes it difficult to research and duplicate efforts to test against a
RegUnknown type so I could clarify it when asked.

The second issue is that, this value in the SAM give, in this particular
location at offset 10, this value is not a type. In this case, perhaps
putting just the value found at this offset first, then putting (Unknown
type) in brackets would clear up the ambiguity. This is similar to how
RegistryViewer does it.

I'll attach a screenshot of what I mean in another comment.

**Comment by Fetchered** [comment]
![RE-SAM-Unknown](https://user-images.githubusercontent.com/10457978/71910915-ca4e0480-3140-11ea-90b4-fdb645d7bbba.png)

**Comment by EricZimmerman** [comment]
There is no reason for it to be explained where it came from, short of a deeper understanding of how the registry works. 

There is no guidance from microsoft as it relates to RegUnknown, but for consistency, i use the same naming convention. in fact, there is no official documentation on anything related to the registry from microsoft, unless something has changed.

it is most certainly a type. thats where the data comes from. just because someone decided to make things work the way they did does not negate the fact that 0x3f1 in your example is being stored in the value type field.

if you use the technical details view its perfectly clear where the data comes from, which is why the details view is there.

I am not concerned with anything Registry Viewer does, because it neither handles deleted keys/values, nor understands transaction logs (in addition to poor searching, single hive at a time, etc). it therefore should never be used for anything.
