### ISSUE TITLE
Exhancement: TLE Timezone support

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#115]
Option to modify timestamps by a timezone would be amazingly useful

**Comment by EricZimmerman** [comment]
Hmm. I dunno.

**Comment by randomaccess3** [comment]
Well it would save me from having to modify it all manually afterwards

**Comment by EricZimmerman** [comment]
What would Phil Hagen do?

**Comment by randomaccess3** [comment]
It wouldnt preclude people from only working in UTC
It would just save those who do time when working with those that dont :)
