### ISSUE TITLE
$J support in MFTECmd requires --csv

### ISSUE THREAD

**Issue by chapinb** [EricZimmerman/Issues#116]
As the title mentions, it appears that MFTECmd v0.4.4.6 requires the `--csv` argument for USN Journal files, even if `--body` is supplied as an output. Let me know of other details to provide!

**Comment by EricZimmerman** [comment]
That's working as intended. Body file only works with  MFT

**Comment by chapinb** [comment]
Understood - Thanks for the quick response!
