### ISSUE TITLE
Kape not finding _kape.cli

### ISSUE THREAD

**Issue by stinkcheese** [EricZimmerman/Issues#117]
Forgive me if this has been covered in another topic, but i am not able to get kape to see my cli file i created.
I have it sitting in the same directory as the kape.exe file and windows also sees it as a batch file. 
From what ive found online, it should just be able to see the cli file, but maybe im doing something wrong?
Any info would be great. 
Thanks!

**Comment by EricZimmerman** [comment]
nothing has changed here. make sure you have file extensions showing in File Explorer so you do not have _kape.cli.txt file which will NOT be used.

**Comment by stinkcheese** [comment]
Got it figured out. Thought that it would have see the name of the file and just processed it even if it was a .bat file, but when i removed the .bat it changed to a CLI file which allowed it to run. 
Thanks for the tip!
