### ISSUE TITLE
TLE Enhancement - command line 

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#120]
Would be awesome to allow for TLE to accept command line options that allow you to filter and output back to CSV/xlsx. 

This way you can save common queries you may run and do the filtering as part of initial processing.
For ex running a query that outputs a CSV of all ZIP files larger than 10mb after you've processed the MFT.

**Comment by EricZimmerman** [comment]
i doubt it. this sounds like grep + adding a header line

**Comment by randomaccess3** [comment]
:( went looking for TLE source to see if I could do it myself. Will have to figure something else out.
