### ISSUE TITLE
KAPE MiniTimeline in Timeline Explorer: Invalid member name

### ISSUE THREAD

**Issue by aleixsb** [EricZimmerman/Issues#125]
Hey!

I'm just trying to create a timeline using the MiniTimeline module in KAPE, but once I get the 01_timeline.csv which has arround 1Gb of data, Timeline explorer fails to open it with the following error:

Error: Invalid member name.

**Comment by aleixsb** [comment]
btw I'm using Timeline explorer v1.0.0.0 and KAPE 0.9.0.0 which are the latest versions

**Comment by EricZimmerman** [comment]
my guess is you are missing a header row.

**Comment by EricZimmerman** [comment]
if this is the case, please close this as its not a TLE issue, its a minitimeline generation issue, and should be brought up with the module author

**Comment by aleixsb** [comment]
Hi Eric,

you are right, thanks for the fast response.
