### ISSUE TITLE
Using KAPE on a Share SMB - Invalid diskName Error

### ISSUE THREAD

**Issue by gregben796** [EricZimmerman/Issues#126]
Hi, 

I’m trying to run KAPE on a mounted image located in a share SMB between my linux virtual machine and my Windows 10 host. I’m using KAPE v0.9.
The idea is to run KAPE without copying the image on Windows (by reaching it directly through the share).

First, I have created the share SMB on my linux vm and I have mounted the image in the share. 

From my host Windows:
 * the share is accessible at `\\192.168.1.135\Share` 
 * the mounted image is accessible at `\\192.168.1.135\Share\mntpoint\cfreds_2015_data_leakage_pc-3-ntfs`
 
However, this network drive was not accessible with KAPE. So, I have created a mapped network drive E: that refers to the share by running (as administrator):
`net use E: \\192.168.1.135\Share`

Then, the share is recognized by KAPE through E: drive (I can find the drive with gkape as well). But I’m facing the following error: 

> Invalid diskName \\.\E

This is the command I run:
`.\kape.exe --tsource E:\mntpoint\cfreds_2015_data_leakage_pc-3-ntfs --tdest C:\forensics\cfreds_dataleakage\kape_analysis --tflush --target RegistryHives`

And this is the error I get:
<img width="952" alt="kape_invaliddiskname" src="https://user-images.githubusercontent.com/40360066/77630175-e779be80-6f4a-11ea-9acf-220e986c1db8.PNG">

Also, I tried to create a symlink of the share using mklink:
`mklink "C:\symlink" "\\192.168.1.135\Share"`

After that, I run the following command:
`.\kape.exe --tsource "C:\symlink\mntpoint\cfreds_2015_data_leakage_pc-3-ntfs" --tdest C:\forensics\cfreds_dataleakage\kape_analysis --tflush --target RegistryHives`

But it does not work neither. The symlink seems to be converted in a wrong path name. Here is the error I get:
<img width="500" alt="kape_symlinkfail" src="https://user-images.githubusercontent.com/40360066/77631283-a5ea1300-6f4c-11ea-9201-6e2dcdf502e9.PNG">

I am running out of ideas right now (maybe try nfs share).
Do you have any idea to solve this issue ?

Thank you.

**Comment by EricZimmerman** [comment]
thats a lot of moving parts. are you mounting the disk under linux with ewfmount or something? i wouldnt do it that way for many reasons. this could be fuse related or any other host of issues

why not just use arsenal image mounter on windows and select the E01 from the share? that way you get physical disk emulation (and vss) without any hassle.

**Comment by gregben796** [comment]
I'm not very experienced with Windows system, so I thought it would be easier to mount the image only on linux on the command line. But you're right, I managed, with arsenal image mounter, to mount my image through the command line directly on Windows. Indeed, it is much easier.

Thank you for your help and quick reply !

**Comment by gregben796** [comment]
Do you know any alternative of arsenal image mounter to decrypt and mount bitlocker drive on Windows ? Because I am using free version and it does not support this feature.

**Comment by EricZimmerman** [comment]
why not just mount it and then use windows to unlock it? once unlocked, image the logical drive letter as needed, or triage
