### ISSUE TITLE
Registry Explorer does not load plugins

### ISSUE THREAD

**Issue by DfirJos** [EricZimmerman/Issues#127]
When starting Registry Explorer v1.5.2.0, I noticed that it did not load any plugins, the error is as follows.

![image](https://user-images.githubusercontent.com/11965973/78897893-2e9b9f80-7a73-11ea-8c29-9899b6900fbf.png)

The same problem applies to the cmd version:

`Error loading plugin: C:\Users\user\Downloads\RegistryExplorer_RECmd\RegistryExplorer\Plugins\RegistryPlugin.7-ZipHistory.dll`

Is there a way to fix this?

**Comment by EricZimmerman** [comment]
yes, do what the download page says! =)

do not use windows to unzip RE as windows blocks the DLLs.

delete the RE folder, use 7zip to extract, and try again

please let me know how it goes and close this when we get it working

**Comment by DfirJos** [comment]
Great, it works. Thank you!
