### ISSUE TITLE
ShellbagExplorer and SBECMD - Has Explored

### ISSUE THREAD

**Issue by klscomputing** [EricZimmerman/Issues#128]
When the same hives are parsed with the GUI and with the command line version of shellbag explorer, the field "has explored" isn't giving the same results. The command line version always reports false - across all hives tried, where the GUI version is giving results. Also question regarding this field...  in the shellbag explorer manual, I can't find a specific definition for "has explored" (when is it true or false) ...   As always, thanks for all the great tools!
![Shellbags explorer v sbecmd has explored](https://user-images.githubusercontent.com/33352413/79261528-85441780-7e7f-11ea-8297-977d5364ebad.JPG)
![Shellbags explorer v sbecmd has explored example 2](https://user-images.githubusercontent.com/33352413/79261549-8c6b2580-7e7f-11ea-8552-663b9ebc307a.JPG)

**Comment by EricZimmerman** [comment]
"has explored" was something that David Cowen and I came up with from what i recall. 

ill check on the CLI version. it was probably just not updated when the GUI was for that column.

shellBag.HasExplored = GetBagsCount(registry,shellBag.NodeSlot) > 2;

private int GetBagsCount(RegistryHive registry,int shellBagNodeSlot)
        {
            var keyPath =
                $"Local Settings\\Software\\Microsoft\\Windows\\Shell\\Bags\\{shellBagNodeSlot}\\Shell";

            var bagKey = registry.GetKey(keyPath);

            if (bagKey == null)
            {
                return 0;
            }

            if (bagKey.SubKeys.Count == 0)
            {
                return 0;
            }

            return bagKey.SubKeys.First().Values.Count;

        }

**Comment by EricZimmerman** [comment]
This is fixed. Pushing update now so check in a few and lemme know.
