### ISSUE TITLE
Timeline Explorer Error on certain CSV file contents

### ISSUE THREAD

**Issue by TroySchnack** [EricZimmerman/Issues#129]
CSV exported from a forensic tool cannot be opened in TLE. I have attached the screenshot and sample CSV (as TXT)
[Export - redacted.txt](https://github.com/EricZimmerman/Issues/files/4533952/Export.-.redacted.txt)
 that causes the error.
![tle error](https://user-images.githubusercontent.com/48991143/80290138-28f7b800-8709-11ea-9f9b-4e518cfa11ec.png)

**Comment by EricZimmerman** [comment]
Is it timeline explorer that's the problem or the CSV?

Does it load elsewhere?

Can you send me the CSV in question via email?

**Comment by TroySchnack** [comment]
It loads fine in Excel, Notepad etc.




Troy Schnack (he/him)
MCFE | ENCE | ACE | CCO | CCPA
Computer System Administrator
Federal Defender

Main:   (816) 471-8282
Direct:   (816) 897-7382
Mobile:  (816) 200-4758

*This e-mail contains PRIVILEGED and CONFIDENTIAL information intended only for the use of the addressee(s) named above.  If you are not the intended recipient of this e-mail, or an authorized employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination or copying of this e-mail is strictly prohibited.  If you have received this e-mail in error, please notify us by reply e-mail. Thank you for your cooperation.

**Comment by EricZimmerman** [comment]
That doesn't even look like a compliant CSV because it's missing double quotes around any of the strings that have spaces in them

can you look online for a CSV compliance check and see if that file passes? If it does I'll take a look but if it doesn't then you need to ask the vendor to make it compliant with the RFC for CSVs

**Comment by TroySchnack** [comment]
OK. I’ll check.


—————————————

Troy Schnack

MCFE EnCE CCO/CCPA ACE

Computer System Admin

Federal Public Defender

Kansas City, MO 64106

Cell 816-200-4758

Sent from my iPhone

On Apr 25, 2020, at 3:39 PM, Eric <notifications@github.com> wrote:

﻿

That doesn't even look like a compliant CSV because it's missing double quotes around any of the strings that have spaces in them

can you look online for a CSV compliance check and see if that file passes? If it does I'll take a look but if it doesn't then you need to ask the vendor to make it compliant with the RFC for CSVs

**Comment by EricZimmerman** [comment]
https://csvlint.io/

**Comment by TroySchnack** [comment]
Original unredacted did have quotes. The problem is a duplicate header name according to https://csvlint.io/



Troy Schnack (he/him)
MCFE | ENCE | ACE | CCO | CCPA
Computer System Administrator
Federal Defender

Main:   (816) 471-8282
Direct:   (816) 897-7382
Mobile:  (816) 200-4758

*This e-mail contains PRIVILEGED and CONFIDENTIAL information intended only for the use of the addressee(s) named above.  If you are not the intended recipient of this e-mail, or an authorized employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination or copying of this e-mail is strictly prohibited.  If you have received this e-mail in error, please notify us by reply e-mail. Thank you for your cooperation.

**Comment by EricZimmerman** [comment]
Ah well in that case whoever the vendor is should fix their duplicate header problem and make them unique

**Comment by EricZimmerman** [comment]
If you manually make the duplicate header unique by adding a one or something else save it and then load it into timeline explorer does it work? If so there's the problem
