### ISSUE TITLE
Feature request for OfficeMRU plugin

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#130]
Would be great to pull out the program and version into an additional column from this plugin.

This can be obtained by looking a few keys up from where the data is stored:
Software\Microsoft\Office\16.0\Excel\User MRU

So the additional column would just say that Excel (16.0) was used to open the file for example 
Low down on the priority list.

**Comment by EricZimmerman** [comment]
this plugin was revised if i recall with more info. what does it look like now?  if not we would need some sample data, will close for now
