### ISSUE TITLE
XWFIM Check for Update failing

### ISSUE THREAD

**Issue by chrisnewmanuk** [EricZimmerman/Issues#132]
![image](https://user-images.githubusercontent.com/7243321/80818077-7fae3780-8bca-11ea-8a70-339fd39dbc5a.png)

**Comment by EricZimmerman** [comment]
You're going to have to just manually download it from my Eric Zimmerman.
Github.io site

I don't know that I maintain the auto updating part anymore

Eric Zimmerman

Opinions stated, unless explicitly stated otherwise, are mine and not that
of my employer.

P // 501-313-3778
