### ISSUE TITLE
PECMD

### ISSUE THREAD

**Issue by madejoh** [EricZimmerman/Issues#134]
Dear Eric, thank you for the several tools,  I am pretty new in the field but just getting my hands busy, I Parsed prefecth directory but got a summary indicating some failed files .
Please what am I not doing right.

Prefetch files was extracted  using FTK imager lite 3.1.1
PECmd.exe is version 1.4.0.0
OS Win10 Ver1903 build 18362.900

![image](https://user-images.githubusercontent.com/66706758/87236217-25a5cb80-c3de-11ea-8a65-e86803694892.png)

**Comment by EricZimmerman** [comment]
You didn't do anything wrong, except for using ftk imager. Hehe.

Sometimes the files are just corrupted and won't parse.

I would try extracting the prefetch files with kape and try again to see
how it goes.

**Comment by madejoh** [comment]
Thanks Eric , your response time is awesome , been extracting on my test lab with FTK ,Im learning (laughs), will read up on Kape, try it out and get back to you.
Thanks again  and Respect
