### ISSUE TITLE
MFT Retrieval

### ISSUE THREAD

**Issue by chrisnewmanuk** [EricZimmerman/Issues#136]
Please add a feature to MTFECMD that can pull+compress the $MFT on a live system

**Comment by EricZimmerman** [comment]
use KAPE and it can do that for you already.

adding that to all my tools is a lot of redundancy

**Comment by chrisnewmanuk** [comment]
Can you update the licence to be clear about commercial business' using it but not using it for profit?

**Comment by EricZimmerman** [comment]
if you charge someone to use KAPE in their environment, you need a license. if in doubt, email kape@kroll.com for clarification, but that is my understanding of how the EULA boils down.

again, if you need that directly from someone here, email kape@kroll.com with your questions.
