### ISSUE TITLE
TLE Enhancement Request: Reset Column Widths Keyboard Shortcut

### ISSUE THREAD

**Issue by 44ops** [EricZimmerman/Issues#137]
Thanks for TLE!

Something I would find immensely useful would be a keyboard shortcut (such as Ctrl+R, Ctrl+W, or anything else) that would Reset Column Widths without the menu. I use this allllllllllllllllllllll the time, and believe it would be a wonderful addition to the several existing shortcuts noted in Quick Help!

**Comment by EricZimmerman** [comment]
done!

**Comment by EricZimmerman** [comment]
TLE: Add CTRL-R shortcut for resize columns command
