### ISSUE TITLE
RECMD/RE - Services Plugin

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#138]
Can you please add an additional column to the services plugin to also provide the contents of the ServiceDLL value under the Parameters subkey as this may be called by a legitimate process and will be overlooked if the examiner only uses RECMD

**Comment by randomaccess3** [comment]
Edit here: See the ServiceDLL is listed to go under Value Data2, but for some reason is empty in the hives I've tested, despite it not being empty. Weird

**Comment by EricZimmerman** [comment]
I'd need a test give and a specific example to look for. That is strange.
May just be missing in the map.

**Comment by EricZimmerman** [comment]
i think this is done now. had someone submit like 10 plugins
