### ISSUE TITLE
Timeline Explorer Loading Timeline - Error Invalid Member name

### ISSUE THREAD

**Issue by theredmoose** [EricZimmerman/Issues#139]
I am getting an error stating, "Error: Invalid Member Name" whenever I try to load a timeline csv file created from kape.  I have tried on multiple systems using different MFT files and still get the same error.  I have also reduced the lines to a very minimum amount and still get the same error.  

1) Create timeline using KAPE - using the following modules
MFTECmd_$MFT_Bodyfile
MFTECmd_TLN
Convert_unicode
Parse_TLN
 
2) Open resulting csv file in Timeline Explorer

**Comment by EricZimmerman** [comment]
probably missing a header row. i would check with mari degrazia as that is her module

**Comment by theredmoose** [comment]
BTW, that was exactly it.
