### ISSUE TITLE
Registry Explorer Feature Requests

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#14]
1. Option to load from mounted drive - iterate through expected locations, option to copy out to case folder.
2. Automatic loading of hive transaction logs (ask if you want to process transaction logs and if yes is selected, go to the same folder that the hive was found and run them through without user interaction. Request new location for the user to save hives).
3. Click the hive path on the left hand pane hides the path of the hive OR option to create an alias for the hive

**Comment by EricZimmerman** [comment]
1. maybe
2. ill change things to automatically apply logs if found in same directory as the hives, else prompt.
3. not sure on this one. what do you mean, "hives the path of hive"? is it too long or something?

**Comment by randomaccess3** [comment]
3. I find the path is a little redundant to have there for the most part. Just means that you end up having to have the left pane a lot wider than it needs to be to display the full path.
Also means if you have multiple Usrclass.dat you can have
Username1_usrclass.dat
Username2_usrclass.dat

instead of
G:\\[root]\users\username1\AppData\Local\Microsoft\Windows\UsrClass.dat
G:\\[root]\users\username2\AppData\Local\Microsoft\Windows\UsrClass.dat

I may be in the minority though.

**Comment by randomaccess3** [comment]
Also 
4. right-click send to ShellbagExplorer from RE since I'm assuming the correct process is to use RE to replay the logs for the usrclass.dat files prior to loading them into SBE.

**Comment by EricZimmerman** [comment]
to 4. no, SBE can automatically process transaction logs (and expects them in the same directory as the hive if its dirty, else you get error messages in SBE). no need to fix in RE then use in SBE. the thing with RE is letting people see and understand the process with replaying logs too, so they know what is going on. all my other registry tools automatically look for (and expect) log files to be present

**Comment by randomaccess3** [comment]
Copy. Good to know.

**Comment by EricZimmerman** [comment]
for 2, in v1.1, if you hold SHIFT while loading or dropping hives and they are dirty the logs will be looked for in the same directory and if found, applied to the in memory hive.

**Comment by EricZimmerman** [comment]
1 is not a function of RE. use kape (coming soon) to harvest hives from a source, then load em
