### ISSUE TITLE
Timeline Explorer [feature request]: time range filter

### ISSUE THREAD

**Issue by forensenellanebbia** [EricZimmerman/Issues#140]
It would be convenient to have a time range filter to quickly find all the events that happened during a date range, but within a specific time frame.

**Comment by EricZimmerman** [comment]
This already exists, has forever =)

click on the little funnel in a datetime column, then Values tab. click the dates or months or years you want. done!

![image](https://user-images.githubusercontent.com/4265254/88944864-459d1200-d25b-11ea-90f9-5bea84b5d784.png)

**Comment by forensenellanebbia** [comment]
Ok, that filter is useful and I'm already using it. But what if I wanted to limit the search to all the events that happened out of business hours from day x to day y? I've tried to use a custom filter from the "Time created" column | Date filters | Custom filter, but the time setting remains fixed and set to **00:00:00** and I can't customize it. Thanks

**Comment by EricZimmerman** [comment]
ah i see. no idea on how to do that one, other than editing the filter once set with button in lower right. 

the filters are set from the grid vendor, devexpress

**Comment by ccjjharmon** [comment]
> Ok, that filter is useful and I'm already using it. But what if I wanted to limit the search to all the events that happened out of business hours from day x to day y? I've tried to use a custom filter from the "Time created" column | Date filters | Custom filter, but the time setting remains fixed and set to **00:00:00** and I can't customize it. Thanks

Actually, I think you may be able to do it in some capacity using DateDiffHour function with the Filter Editor - see attached screenshot where I'm only showing the 22nd hour for 1/28/2024.... little hokey but it is *something*
![filtereditor_22ndhour](https://github.com/EricZimmerman/Issues/assets/624371/f3b4a1b1-a7d7-45ed-82d2-07f7c4fa0422)

**Comment by EricZimmerman** [comment]
Use the search in upper right with an exact timestamp. There is no other way that I know of.

**Comment by ccjjharmon** [comment]
Eric I'm saying you can do a time filter .... but it just requires using some functions within the Filter Editor. Here's a little complicated example I just used:

[Time Created] >= #2024-01-28# And [Time Created] <= #2024-01-29# And DateDiffHour(#2024-01-28#, [Time Created]) = 22 And DateDiffMinute(#2024-01-28 22:00:00#, [Time Created]) > 25 And DateDiffMinute(#2024-01-28 22:00:00#, [Time Created]) < 29

that will return all events between 1/28/2024 22:25:00 and 22:29:00. It definitely works.

**Comment by 6lagoon6** [comment]
You can do it like this:
<img width="462" height="52" alt="Image" src="https://github.com/user-attachments/assets/4fad6d9b-b655-45f7-841b-f744e6c6cef0" />
