### ISSUE TITLE
Bstrings URL search

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#142]
Unsure if I'm doing this correctly but running a search in bstrings using the URL example: bstrings.exe -f "C:\Temp\UsrClass 1.dat" --ls URL

It's returning no hits

If I run regular bstrings, and then just grep for things, I can see URLs

**Comment by EricZimmerman** [comment]
--lr url3986

LS is look for string not regex

**Comment by EricZimmerman** [comment]
LS url just looks for the string

Url

Vs pattern matching via regex

**Comment by randomaccess3** [comment]
Copy. Yeah tried to the --lr and it worked.
