### ISSUE TITLE
Timeline explorer fails to load plaso csv - "String was not recognized as a valid DateTime"

### ISSUE THREAD

**Issue by ydkhatri** [EricZimmerman/Issues#143]
Hi Eric
Tried to load a plaso csv file today. Got this error:
<img width="215" alt="Screen Shot 2020-08-20 at 8 16 11 PM" src="https://user-images.githubusercontent.com/13247440/90838149-16d9ff00-e322-11ea-8458-24af0d9f5d43.png">

The start of the file seems valid, I tried manually chopping it to a few thousand line items and that loaded fine. Not sure where the error in the file is.

It would be helpful to get a line number in the error, so we can try to debug, or perhaps auto-exclude that line, or blank the field and continue parsing..

**Comment by EricZimmerman** [comment]
Most likely it's missing a timestamp somewhere. 

Is it possible to share the file so I can try to add a more meaningful error message?

**Comment by ydkhatri** [comment]
> Is it possible to share the file so I can try to add a more meaningful error message?

Not publicly. Drop me an email and I can reply to it - yogesh@swiftforensics.com

**Comment by EricZimmerman** [comment]
This is related to plaso generating bad timestamps. this is not a valid date time:

00/00/0000,--:--:--,

i added a workaround to assume 0 when the data is bad.

i also added a better warning:

![image](https://user-images.githubusercontent.com/4265254/90842541-8f928880-e32d-11ea-9376-4a56e4f0cadd.png)

update should be up in a bit

**Comment by EricZimmerman** [comment]
1.0.0.2 released
