### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by kimmoal** [EricZimmerman/Issues#145]
Hello!

raising a separate issue from #119 where you mention porting to .NET Core in the future
Some advantages for this are:

- Possibly run on Linux platform, Kali for example
- Container support, one would be able to run EZTools for mass analysis in the cloud for example

This would benefit DFIR people greatly, if you need help I can see what I can do.

Possible blocker is also `RawCopy_ERZ_2_2_32.dll` dependency which I cannot find from anywhere, so it might not be compatible with Linux platform

Thank you!

**Comment by EricZimmerman** [comment]
this is a chicken and egg problem. i like the idea of .net core support, but that leaves many people having to install that runtime on their end points, so work remains to evaluate how to best handle this.

as to rawcopy, i would just not compile that into the non-windows version, as it relates to raw disk reads for NTFS.

**Comment by kimmoal** [comment]
> this is a chicken and egg problem. i like the idea of .net core support, but that leaves many people having to install that runtime on their end points, so work remains to evaluate how to best handle this.

I am under the impression that you can potentially support both .NET Framework and .NET Core versions with separate builds,
reading from here: https://docs.microsoft.com/en-us/dotnet/core/porting/

... but this also could entail some #if #else compiler trickery and dependencies not being compatible. I am not a .NET person myself and not familiar with the codebase(s) so I cannot evaluate how much work this would generate.

**Comment by EricZimmerman** [comment]
this be DONE!
