### ISSUE TITLE
EvtxECmd - xpath query syntax

### ISSUE THREAD

**Issue by forensenellanebbia** [EricZimmerman/Issues#148]
I'm writing a few maps and would like to extract the value from "Correlation ActivityID". I've made a few attempts, but I can't figure out what XPath query I have to write to achieve that. 

```
<Event>
  <System>
    <Provider Name="Microsoft-Windows-TerminalServices-LocalSessionManager" Guid="5d896912-022d-40aa-a3a8-4fa5515c76d7" />
    <EventID>24</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x1000000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-17 17:18:43.0841330" />
    <EventRecordID>1117</EventRecordID>
    <Correlation ActivityID="f420deb9-1cf8-47d9-9c2a-1ff2c4560000" />
    <Execution ProcessID="1164" ThreadID="2500" />
    <Channel>Microsoft-Windows-TerminalServices-LocalSessionManager/Operational</Channel>
    <Computer>MYPC</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <UserData>
    <EventXML>
      <User>MYPC\user</User>
      <SessionID>1</SessionID>
      <Address>192.168.1.100</Address>
    </EventXML>
  </UserData>
</Event>
```

**Comment by EricZimmerman** [comment]
how about this?

/Event/System/Correlation/@ActivityID

**Comment by forensenellanebbia** [comment]
This is what I added to the existing Microsoft-Windows-TerminalServices-LocalSessionManager_Operational_24.map map file:
```
  - 
    Property: PayloadData2
    PropertyValue: "Activity ID: %ActivityID%"
    Values: 
      - 
        Name: ActivityID
        Value: "/Event/System/Correlation/@ActivityID"
```
I then ran Evtxecmd (0.6.0.2) and received a lot of these messages:
```
Record # 37 (Event Record Id: 37): In map for event '24', Property '/Event/System/Correlation/@ActivityID' not found! Replacing with empty string
Record # 118 (Event Record Id: 118): In map for event '24', Property '/Event/System/Correlation/@ActivityID' not found! Replacing with empty string

```
And PayloadData2 in the CSV output file remained empty.

**Comment by EricZimmerman** [comment]
Try altova xmlspy trial and see what xoath statement it provides for that attrobute

**Comment by EricZimmerman** [comment]
maybe this?

string(/Event/System/Correlation/@ActivityID)

**Comment by forensenellanebbia** [comment]
I tried it on [freeformatter ](https://www.freeformatter.com/xpath-tester.html#ad-output) and worked.

![Free Online XPath](https://user-images.githubusercontent.com/8271353/100162041-f5555a00-2eb2-11eb-86f0-8d328e75487b.png)

But it failed when I ran it inside the map file:
```
Errors
Record #37: Error: Expression must evaluate to a node-set.
```

As a test, I also tried to extract Opcode but I always end up with _Property '/Event/System/Opcode' not found! Replacing with empty string_

**Comment by EricZimmerman** [comment]
you can send me the evtx and i can see if i can figure it out if you like

**Comment by forensenellanebbia** [comment]
I prepared some test data. The file contains a few RDP events with Correlation ActivityIDs. Thanks in advance

[Microsoft-Windows-TerminalServices-RDPClient_Operational.zip](https://github.com/EricZimmerman/Issues/files/5593505/Microsoft-Windows-TerminalServices-RDPClient_Operational.zip)

**Comment by EricZimmerman** [comment]
i see why its failing now. its only using maps for the EventData or UserData section of the XML, not all the XML.

i switched it to look at the entire XML string, so now this, as of v0.6.0.3, works as youd expect:

```
Maps: 
  - 
    Property: PayloadData1
    PropertyValue: "Dest: %DestServer% AID: %ActivityID%"
    Values: 
      - 
        Name: DestServer
        Value: "/Event/EventData/Data[@Name=\"Value\"]"
      - 
        Name: ActivityID
        Value: "/Event/System/Correlation/@ActivityID"
```

Dest: 11.1.1.12 AID: bf5eca37-4580-4e58-9697-e3573b410000
