### ISSUE TITLE
WxTCmd (version 0.6.0.0) exports CSV encoded in UCS-2

### ISSUE THREAD

**Issue by Qazeer** [EricZimmerman/Issues#149]
Hello,

WxTCmd (version 0.6.0.0) exports the Activity.csv and Activity_PackageIDs.csv CSV encoded in UCS-2 (according to Notepad++).

While the files can be properly opened with TimelineExplorer / Excel, it causes issues with some third party tools.

Would it be possible to provide an option (or force) encoding of exported CSV in UTF-8?

Best regards,

**Comment by EricZimmerman** [comment]
What third party tools? The default should be unicode so not sure why some tools have issues. 

I'll see what I can do to force utf8

**Comment by Qazeer** [comment]
Namely [Vector from Timberio](https://github.com/timberio/vector), which I use to send the CSV to an ELK stack. 
The CSV parsing, which works fine for others outputs from your tooling, does not work with WxTCmd's CSV output.

I am quite sure it could be fixed Vector side or simply by directly converting the file in UTF-8 though.

**Comment by EricZimmerman** [comment]
i would say Vector is broken if it does not understand UTF16

right now the files are encoded as UTF-16LE:

```
using (var sw = new StreamWriter(aoesOut, false, Encoding.Unicode))
```

which results in this:

![image](https://user-images.githubusercontent.com/4265254/103094533-d0e0c080-45cb-11eb-84c2-f88fc141aaba.png)

i changed it to

```
using (var sw = new StreamWriter(apesOut, false, Encoding.UTF8))
```
![image](https://user-images.githubusercontent.com/4265254/103094869-c4a93300-45cc-11eb-871a-c83f9b7dfe67.png)


update and give it a whirl

**Comment by Qazeer** [comment]
It works, thank you very much!
