### ISSUE TITLE
RECMD WordWheelQuery plugin: Add lastwrite time for MRU 0 item to plugin

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#151]
Would be useful to add the lastwrite timestamp for the Wordwheelquery key to the MRU 0 item within the plugin itself. 

See bad paint skillz
![image](https://user-images.githubusercontent.com/1241363/103506423-c8806380-4eb0-11eb-9ab5-b36922a8c0fb.png)

**Comment by EricZimmerman** [comment]
done, but the value is already shown in lower left corner too

![image](https://user-images.githubusercontent.com/4265254/114873697-8f1d9500-9dc9-11eb-8cd8-f78da816a55d.png)
