### ISSUE TITLE
EVTXECMD - OAlerts map regex doesn't work for all cases

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#152]
Unsure how to fix this

![image](https://user-images.githubusercontent.com/1241363/103508338-ecde3f00-4eb4-11eb-9fd2-f1e11757c20f.png)

Some of the filenames have a special character in front (unintentionally, or by design in my last test with the #).

If that happens then the map for Payload2 falls over

![image](https://user-images.githubusercontent.com/1241363/103508443-17c89300-4eb5-11eb-9d7f-896914d69f24.png)

**Comment by EricZimmerman** [comment]
seems like a regex issue to me and not map related

pull the odata stuff into a text file, load up RegExBuddy, and play with the regex until you can get it to match both.
