### ISSUE TITLE
EvtxECmd - 'Provider' must not be empty

### ISSUE THREAD

**Issue by j5jb3x4eys** [EricZimmerman/Issues#153]
```
i have run across this error several times recently across several different (windows 10) devices

example:
Command line: -d C:\Windows\System32\winevt\Logs\ --sd 2020-12-15 00:00:01 --ed 2020-12-15 23:59:59 --csv c:\temp --csvf c:\temp\201215-eventlogs.csv

Setting Start date to '2020-12-15 00:00:01.0000000'
Setting End date to '2020-12-15 23:59:59.0000000'

CSV output will be saved to 'c:\temp\201215-eventlogs.csv'


C:\Quarantine\tools\kape\Modules\bin\EvtxECmd\Maps\Application-Audit-CVE_1.map had validation errors:
'Provider' must not be empty.

Correct the errors and try again. Exiting

C:\Quarantine\tools\kape\Modules\bin\EvtxECmd\Maps\WindowsDefender_5007.map had validation errors:
'Provider' must not be empty.

Correct the errors and try again. Exiting
...

before running, i ran
Get-KAPEUpdate.ps1
.\kape.exe --sync

fails and doesn't return anything

any help in figuring this out would be appreciated
```

**Comment by EricZimmerman** [comment]
delete all maps

do a --sync

fixed

kapeupdate does not update the stuff under modules, but i will push an update to existing KAPE that includes all map fixes

**Comment by EricZimmerman** [comment]
that of course would be in modules\bin\evtxecmd dir

**Comment by j5jb3x4eys** [comment]
thank you

**Comment by j5jb3x4eys** [comment]
did as instructed, updated all maps, still returns 0 logs (see attached)

[evtxecmd_errors-output.txt](https://github.com/EricZimmerman/Issues/files/5816564/evtxecmd_errors-output.txt)
[201215-eventlogs.xlsx](https://github.com/EricZimmerman/Issues/files/5816565/201215-eventlogs.xlsx)

thanks in advance for the help

**Comment by EricZimmerman** [comment]
1. drop the date ranges to test
2.  --csvf expects JUST a filename, not a full path. this may be your primary issue

--csvf 201215-eventlogs.csv

start with 2 i suppose and go from there.

**Comment by AndrewRathbun** [comment]
I am curious why that's an XLSX document and not a CSV? Did you change the file extension? For what reason, if so?

Make sure you have the latest binary for EvtxECmd in the KAPE\Modules\bin folder. Make sure all maps are updated in that folder via EvtxECmd --sync. Also, what Eric just said above.

**Comment by EricZimmerman** [comment]
look at your date ranges too.

Events dropped: 1,782

over and over and over. maybe your range is not within the dates in the logs. thats why i said to drop them to start

**Comment by EricZimmerman** [comment]
here is your problem. no records included

D:\!Downloads\evtxecmd_errors-output.txt
      30  Records included: 0 Errors: 0 Events dropped: 0
      45  Records included: 0 Errors: 0 Events dropped: 1,782
     135  Records included: 0 Errors: 0 Events dropped: 1,786
     154  Records included: 0 Errors: 0 Events dropped: 1,828
     177  Records included: 0 Errors: 0 Events dropped: 2,206
     206  Records included: 0 Errors: 0 Events dropped: 2,352
     229  Records included: 0 Errors: 0 Events dropped: 2,352
     248  Records included: 0 Errors: 0 Events dropped: 2,424
     272  Records included: 0 Errors: 0 Events dropped: 3,098
     302  Records included: 0 Errors: 0 Events dropped: 3,389
     339  Records included: 0 Errors: 0 Events dropped: 3,435
     368  Records included: 0 Errors: 0 Events dropped: 5,517
     389  Records included: 0 Errors: 0 Events dropped: 9,281
     467  Records included: 0 Errors: 0 Events dropped: 9,810
     495  Records included: 0 Errors: 0 Events dropped: 9,838
     514  Records included: 0 Errors: 0 Events dropped: 9,842
     533  Records included: 0 Errors: 0 Events dropped: 9,907
     552  Records included: 0 Errors: 0 Events dropped: 9,913
     574  Records included: 0 Errors: 0 Events dropped: 9,921
     639  Records included: 0 Errors: 0 Events dropped: 10,047
     668  Records included: 0 Errors: 0 Events dropped: 10,074
     693  Records included: 0 Errors: 3 Events dropped: 10,074
     715  Records included: 0 Errors: 0 Events dropped: 10,097
     735  Records included: 0 Errors: 0 Events dropped: 10,910
     757  Records included: 0 Errors: 0 Events dropped: 10,912
     776  Records included: 0 Errors: 0 Events dropped: 10,914
     795  Records included: 0 Errors: 0 Events dropped: 10,994
     817  Records included: 0 Errors: 0 Events dropped: 10,994
     832  Records included: 0 Errors: 0 Events dropped: 11,091
     850  Records included: 0 Errors: 0 Events dropped: 11,093
     869  Records included: 0 Errors: 0 Events dropped: 11,366
     904  Records included: 0 Errors: 0 Events dropped: 12,681
     976  Records included: 0 Errors: 0 Events dropped: 12,733
    1000  Records included: 0 Errors: 0 Events dropped: 12,804
    1020  Records included: 0 Errors: 0 Events dropped: 12,811
    1040  Records included: 0 Errors: 0 Events dropped: 12,811
    1055  Records included: 0 Errors: 0 Events dropped: 12,940
    1078  Records included: 0 Errors: 0 Events dropped: 14,932
    1105  Records included: 0 Errors: 0 Events dropped: 15,163
    1130  Records included: 0 Errors: 0 Events dropped: 19,858
    1193  Records included: 0 Errors: 0 Events dropped: 19,885
    1225  Records included: 0 Errors: 0 Events dropped: 19,935
    1614  Records included: 0 Errors: 0 Events dropped: 20,563
    1648  Records included: 0 Errors: 0 Events dropped: 20,594
    1676  Records included: 0 Errors: 0 Events dropped: 20,606
    1696  Records included: 0 Errors: 0 Events dropped: 21,209
    1717  Records included: 0 Errors: 0 Events dropped: 21,347
    1743  Records included: 0 Errors: 0 Events dropped: 21,375
    1764  Records included: 0 Errors: 0 Events dropped: 21,377
    1783  Records included: 0 Errors: 0 Events dropped: 21,382
    1802  Records included: 0 Errors: 0 Events dropped: 21,401
    1826  Records included: 0 Errors: 0 Events dropped: 22,246
    1850  Records included: 0 Errors: 0 Events dropped: 22,248
    1869  Records included: 0 Errors: 0 Events dropped: 22,252
    1891  Records included: 0 Errors: 0 Events dropped: 22,256
    1914  Records included: 0 Errors: 0 Events dropped: 22,374
    1936  Records included: 0 Errors: 0 Events dropped: 22,383
    1957  Records included: 0 Errors: 0 Events dropped: 22,393
    1979  Records included: 0 Errors: 0 Events dropped: 22,393
    1994  Records included: 0 Errors: 0 Events dropped: 22,446
    2029  Records included: 0 Errors: 0 Events dropped: 23,973
    2091  Records included: 0 Errors: 0 Events dropped: 23,975
    2110  Records included: 0 Errors: 0 Events dropped: 23,975
    2125  Records included: 0 Errors: 0 Events dropped: 24,021
    2149  Records included: 0 Errors: 0 Events dropped: 24,033
    2171  Records included: 0 Errors: 0 Events dropped: 24,045
    2191  Records included: 0 Errors: 0 Events dropped: 24,048
    2216  Records included: 0 Errors: 0 Events dropped: 24,082
    2235  Records included: 0 Errors: 0 Events dropped: 24,641
    2261  Records included: 0 Errors: 0 Events dropped: 24,642
    2280  Records included: 0 Errors: 0 Events dropped: 24,874
    2311  Records included: 0 Errors: 0 Events dropped: 24,874
    2326  Records included: 0 Errors: 0 Events dropped: 24,913
    2345  Records included: 0 Errors: 0 Events dropped: 24,913
    2360  Records included: 0 Errors: 0 Events dropped: 25,330
    2393  Records included: 0 Errors: 0 Events dropped: 25,341
    2421  Records included: 0 Errors: 0 Events dropped: 25,360
    2447  Records included: 0 Errors: 0 Events dropped: 25,361
    2474  Records included: 0 Errors: 0 Events dropped: 25,368
    2495  Records included: 0 Errors: 0 Events dropped: 25,370
    2514  Records included: 0 Errors: 0 Events dropped: 26,012
    2555  Records included: 0 Errors: 0 Events dropped: 26,106
    2575  Records included: 0 Errors: 0 Events dropped: 26,109
    2594  Records included: 0 Errors: 0 Events dropped: 26,306
    2623  Records included: 0 Errors: 0 Events dropped: 26,309
    2647  Records included: 0 Errors: 0 Events dropped: 31,867
    2682  Records included: 0 Errors: 0 Events dropped: 31,871
    2701  Records included: 0 Errors: 0 Events dropped: 58,708
    2731  Records included: 0 Errors: 0 Events dropped: 58,767
    2751  Records included: 0 Errors: 0 Events dropped: 58,767
    2766  Records included: 0 Errors: 0 Events dropped: 58,804
    2795  Records included: 0 Errors: 0 Events dropped: 58,813
    2817  Records included: 0 Errors: 0 Events dropped: 58,895
    2844  Records included: 0 Errors: 0 Events dropped: 59,216
    2871  Records included: 0 Errors: 0 Events dropped: 59,295
    2897  Records included: 0 Errors: 0 Events dropped: 59,333
    2924  Records included: 0 Errors: 0 Events dropped: 59,346
    2946  Records included: 0 Errors: 0 Events dropped: 59,368
    2968  Records included: 0 Errors: 0 Events dropped: 59,404
    2997  Records included: 0 Errors: 0 Events dropped: 59,407
    3017  Records included: 0 Errors: 0 Events dropped: 59,409
    3048  Records included: 0 Errors: 0 Events dropped: 59,945
    3080  Records included: 0 Errors: 0 Events dropped: 59,964
    3103  Records included: 0 Errors: 0 Events dropped: 60,175
    3123  Records included: 0 Errors: 0 Events dropped: 60,176
    3142  Records included: 0 Errors: 0 Events dropped: 60,308
    3164  Records included: 0 Errors: 0 Events dropped: 60,316
    3186  Records included: 0 Errors: 0 Events dropped: 60,345
    3216  Records included: 0 Errors: 0 Events dropped: 60,363
    3244  Records included: 0 Errors: 0 Events dropped: 61,686
    3265  Records included: 0 Errors: 0 Events dropped: 61,753
    3296  Records included: 0 Errors: 0 Events dropped: 61,771
    3316  Records included: 0 Errors: 0 Events dropped: 64,078
    3357  Records included: 0 Errors: 0 Events dropped: 64,089
    3377  Records included: 0 Errors: 0 Events dropped: 64,103
    3400  Records included: 0 Errors: 0 Events dropped: 65,493
    3519  Records included: 0 Errors: 0 Events dropped: 66,266

**Comment by j5jb3x4eys** [comment]
> I am curious why that's an XLSX document and not a CSV? Did you change the file extension? For what reason, if so?
> 
> Make sure you have the latest binary for EvtxECmd in the KAPE\Modules\bin folder. Make sure all maps are updated in that folder via EvtxECmd --sync. Also, what Eric just said above.

because github doesn't accept csv as a file upload type... had to save it as an accepted type

![image](https://user-images.githubusercontent.com/75484438/104641224-b946a600-5666-11eb-9270-85f77a9392aa.png)

![image](https://user-images.githubusercontent.com/75484438/104640636-f78f9580-5665-11eb-9d25-ff35a1342a8a.png)

**Comment by EricZimmerman** [comment]
ah, would have been enough to say its empty =)

**Comment by AndrewRathbun** [comment]
> 
> 
> > I am curious why that's an XLSX document and not a CSV? Did you change the file extension? For what reason, if so?
> > Make sure you have the latest binary for EvtxECmd in the KAPE\Modules\bin folder. Make sure all maps are updated in that folder via EvtxECmd --sync. Also, what Eric just said above.
> 
> because github doesn't accept csv as a file upload type... had to save it as an accepted type
> 
> ![image](https://user-images.githubusercontent.com/75484438/104641224-b946a600-5666-11eb-9270-85f77a9392aa.png)
> 
> ![image](https://user-images.githubusercontent.com/75484438/104640636-f78f9580-5665-11eb-9d25-ff35a1342a8a.png)

Huh, interesting. Thanks for pointing that out!
