### ISSUE TITLE
KAPE: allow the use of the --sync despite a _kape.cli is found

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/Issues#155]
Proposal: Ignore _kape.cli if the --sync is given.

**Comment by EricZimmerman** [comment]
why?

--sync wins over everything

worst case, add a --sync to the top of your _kape.cli and it does the same thing, no?

**Comment by Karneades** [comment]
ok, I see, sync will be performed but the commands in _kape.cli too. I only manually update the packages (for testing, checking the diff). I have to rename _kape.cli to only update the packages and not run all the commands too - no big deal, of course. it would make it easier for my workflow to update if _kape.cli is ignored when --sync is given. but I guess most of the other users use the --sync each time they run the tool?

**Comment by EricZimmerman** [comment]
i would say not even close to every time.
