### ISSUE TITLE
gkape: Add button to remove a module variable

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/Issues#156]
When using gkape and module variables, the addition of new variables is possible, but the removal isn't possible. It would be convenient if there's a button to remove variables too.

**Comment by Karneades** [comment]
I found out, that using "delete" key stroke, it's possible to remove them, but that's not visible at first glance, maybe a short text below the input field? Otherwise it's working for me with the del key stroke.

**Comment by EricZimmerman** [comment]
hover over things and tool tips show up. is it not mentioned there?

**Comment by Karneades** [comment]
I'm very sorry that I missed this tool tip... :| Yes, it's shown there :+1:
