### ISSUE TITLE
REGISTRY - KeyPath, KeyName or ValueName containing '|' makes ExportDataToCommonFormat unparseable

### ISSUE THREAD

**Issue by raboni84** [EricZimmerman/Issues#157]
**How to reproduce the error:**

- Download a development IE 11 Win 7 VirtualBox-VM
- Use 7-Zip GUI to extract the VMDK disk from the OVA
- Use 7-Zip GUI to extract the SYSTEM RegistryHive from the VMDK
- Use the "ExportDataToCommonFormat" function from the RegistryHive class to dump the hives contents with enabled "RecoverDeleted" and "FlushRecordListsAfterParse"
- Try parsing the contents back based on the documented layout in the header of the file

**Result:**

The file contains the following lines, which are not parseable by the documented layout because of the additional "pipe" chars:
- `value|A|6964368|USR|Control Panel|Desktop|LogPixels|4|04 00 00 00`
- `value|A|6964000|USR|Software|Microsoft|ClientForNFS|CurrentVersion|Default|DisplayAllLinks|4|04 00 00 00`
- `value|A|5351504|USR|Software|Microsoft|ClientForNFS|CurrentVersion|Default|DeleteSymlinks|4|04 00 00 00`
- ...

Based on this you cannot tell where the path ends and the name starts to autocorrect the line.

**A solution to this problem could be:**

Simply escape the containing pipes by surrounding the value by double quotes (`"..."`) and escape containing double quotes by doubling them. This is based on the principle of CSV files containing commas in column values.

**Comment by EricZimmerman** [comment]
That export method was a bit getto. I'll add a real rfc compliant export. I can stick with pipe or just use csv. Preference?

**Comment by raboni84** [comment]
Hmmm, in the end it would make no difference if the export would be a pipe or a comma separated version. The advantage of comma separated values would be it's widespread use in database tools and table software imports and exports. You could for example import everything into a SQL database.

Exporting into a completely different format like JSON on the other hand would make the whole value handling more user friendly as numbers, strings and even "zero separated" string arrays could easily be supported instead of converting everything into a hex string. When everything is written out in it's actual value representation or maybe base64 for binary the idea of using something like Elasticsearch would be possible without the need of some conversion software.

**Comment by EricZimmerman** [comment]
the commonformat idea was so authors could compare their output with others, looking for discrepancies.

if you want to export out entire hives as json you can already do that via recmd.

**Comment by AndrewRathbun** [comment]
@raboni84 if you're using KAPE, you can leverage the KapeResearch Modules that were recently created. Find them here: https://github.com/EricZimmerman/KapeFiles/tree/master/Modules/KapeResearch

Note, the UsrClass Module will have to be edited on your own for it to work. The ROOT key is not called ROOT, rather, it's a SID of sorts, so you'll have to see what it is on your target system and place it in the Module for it to dump successfully. Same with RECmd, you can dump to JSON but you'll need to know what that ROOT key is called. 

The rest of the Modules work out of the box, so to speak. They just recursively dump ROOT for each respective hive. Very useful!

**Comment by EricZimmerman** [comment]
so if i add rfc compliant export of this format, its going to add a dependency to csvhelper. the other side of this is i would then need two different csvs, one for keys, one for values.

the intent again was to export out data to a common text format and then diff the 2 files, vs export import. there are better ways to implement that kind of thing, up to and including how i do it in recmd to json, csv, batch mode, etc.

i dont want to change this method for the reasons above

**Comment by raboni84** [comment]
Oh, okay that's understandable. Thank you for your time anyways. As I don't want to use a console application as a library reference in my project, my idea was to link only to Registry and would be finished.

As it is now I have created a patch to modify the code not to write pipes but escape the CSV values that are in need to. No need for an additional library like CsvHelper as the export is so simple in nature.

With this modification, it is still common-format-comparable while being more common format. I included the git diff below. Again, thank you for your time.

-- raboni84

```diff
diff --git a/Registry/RegistryHive.cs b/Registry/RegistryHive.cs
index b7432e1..73954f5 100644
--- a/Registry/RegistryHive.cs
+++ b/Registry/RegistryHive.cs
@@ -98,15 +98,15 @@ namespace Registry
 
                 keyCount += 1;
 
-                sw.WriteLine("key|{0}|{1}|{2}|{3:o}", subkey.NkRecord.IsFree ? "U" : "A",
-                    subkey.NkRecord.AbsoluteOffset, subkey.KeyPath, subkey.LastWriteTime?.UtcDateTime);
+                sw.WriteLine("key,{0},{1},{2},{3:o}", subkey.NkRecord.IsFree ? "U" : "A",
+                    subkey.NkRecord.AbsoluteOffset, GetCsvValue(subkey.KeyPath), subkey.LastWriteTime?.UtcDateTime);
 
                 foreach (var val in subkey.Values)
                 {
                     valueCount += 1;
 
-                    sw.WriteLine(@"value|{0}|{1}|{2}|{3}|{4}|{5}", val.VkRecord.IsFree ? "U" : "A",
-                        val.VkRecord.AbsoluteOffset, subkey.KeyName, val.ValueName, (int) val.VkRecord.DataType,
+                    sw.WriteLine(@"value,{0},{1},{2},{3},{4},{5}", val.VkRecord.IsFree ? "U" : "A",
+                        val.VkRecord.AbsoluteOffset, GetCsvValue(subkey.KeyName), GetCsvValue(val.ValueName), (int) val.VkRecord.DataType,
                         BitConverter.ToString(val.VkRecord.ValueDataRaw).Replace("-", " "));
                 }
 
@@ -698,16 +698,16 @@ namespace Registry
                     if (Root.LastWriteTime != null)
                     {
                         keyCount = 1;
-                        sw.WriteLine("key|{0}|{1}|{2}|{3}", Root.NkRecord.IsFree ? "U" : "A",
+                        sw.WriteLine("key,{0},{1},{2},{3}", Root.NkRecord.IsFree ? "U" : "A",
                             Root.NkRecord.AbsoluteOffset,
-                            Root.KeyPath, Root.LastWriteTime.Value.UtcDateTime.ToString("o"));
+                            GetCsvValue(Root.KeyPath), Root.LastWriteTime.Value.UtcDateTime.ToString("o"));
                     }
 
                     foreach (var val in Root.Values)
                     {
                         valueCount += 1;
-                        sw.WriteLine(@"value|{0}|{1}|{2}|{3}|{4}|{5}", val.VkRecord.IsFree ? "U" : "A",
-                            val.VkRecord.AbsoluteOffset, Root.KeyPath, val.ValueName, (int) val.VkRecord.DataType,
+                        sw.WriteLine(@"value,{0},{1},{2},{3},{4},{5}", val.VkRecord.IsFree ? "U" : "A",
+                            val.VkRecord.AbsoluteOffset, GetCsvValue(Root.KeyPath), GetCsvValue(val.ValueName), (int) val.VkRecord.DataType,
                             BitConverter.ToString(val.VkRecord.ValueDataRaw).Replace("-", " "));
                     }
 
@@ -726,9 +726,9 @@ namespace Registry
                             valueCountDeleted += 1;
                             var val = keyValuePair.Value as VkCellRecord;
 
-                            sw.WriteLine(@"value|{0}|{1}|{2}|{3}|{4}|{5}", val.IsFree ? "U" : "A", val.AbsoluteOffset,
-                                "",
-                                val.ValueName, (int) val.DataType,
+                            sw.WriteLine(@"value,{0},{1},{2},{3},{4},{5}", val.IsFree ? "U" : "A", val.AbsoluteOffset,
+                                string.Empty,
+                                GetCsvValue(val.ValueName), (int) val.DataType,
                                 BitConverter.ToString(val.ValueDataRaw).Replace("-", " "));
                         }
 
@@ -740,8 +740,8 @@ namespace Registry
                             var nk = keyValuePair.Value as NkCellRecord;
                             var key = new RegistryKey(nk, null);
 
-                            sw.WriteLine("key|{0}|{1}|{2}|{3}", key.NkRecord.IsFree ? "U" : "A",
-                                key.NkRecord.AbsoluteOffset, key.KeyName,
+                            sw.WriteLine("key,{0},{1},{2},{3}", key.NkRecord.IsFree ? "U" : "A",
+                                key.NkRecord.AbsoluteOffset, GetCsvValue(key.KeyName),
                                 key.LastWriteTime.Value.UtcDateTime.ToString("o"));
 
                             DumpKeyCommonFormat(key, sw, ref keyCountDeleted, ref valueCountDeleted);
@@ -754,13 +754,23 @@ namespace Registry
                     }
                 }
 
-                sw.WriteLine("total_keys|{0}", keyCount);
-                sw.WriteLine("total_values|{0}", valueCount);
-                sw.WriteLine("total_deleted_keys|{0}", keyCountDeleted);
-                sw.WriteLine("total_deleted_values|{0}", valueCountDeleted);
+                sw.WriteLine("total_keys,{0}", keyCount);
+                sw.WriteLine("total_values,{0}", valueCount);
+                sw.WriteLine("total_deleted_keys,{0}", keyCountDeleted);
+                sw.WriteLine("total_deleted_values,{0}", valueCountDeleted);
             }
         }
 
+        private static readonly string quote = "\"";
+        private static readonly string doublequote = "\"\"";
+
+        private string GetCsvValue(string value)
+        {
+            if (value.Any(x => x == ',' || x == '"' || x == '\n'))
+                value = string.Concat(quote, value.Replace(quote, doublequote), quote);
+            return value;
+        }
+
         public RegistryKey GetDeletedKey(long relativeOffset, long lastwritetimestampTicks)
         {
            // var segs = keyPath.Split('\\');
```

**Comment by EricZimmerman** [comment]
You can do a PR with the changes if you like unless you just forked it and made it for your needs

If you want json, reference ServiceStack.Text and pull the root key abstraction (or the full keys if you want eeeeevvvverything) and use the extension method to convert to json.
