### ISSUE TITLE
RecentFileCacheParser index/count error

### ISSUE THREAD

**Issue by jipegit** [EricZimmerman/Issues#158]
Version: `1.0.0.0`
Error encountered:
```
Error: Index and count must refer to a location within the buffer.
Parameter name: bytes
```

**Comment by EricZimmerman** [comment]
Not helpful without the file that caused the error. Can you send it to me?

**Comment by jipegit** [comment]
Unfortunately I can't share the file. Closing the issue if having the parameter alone is not helpful.

**Comment by EricZimmerman** [comment]
Not at all. I have nothing to go on

that file generally just contains file names and timestamps so I'm not sure why you can't share it but it is what it is
