### ISSUE TITLE
PECMD - CSV output having a column for full path

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#162]
Would be useful in the CSV to have the full path for the exe also included, similarly to how it's highlighted in the standard output.

**Comment by EricZimmerman** [comment]
this would not always work, as sometimes the same exe name shows up in the file output.

**Comment by randomaccess3** [comment]
I'm not following why this wouldn't work. It would make getting a timeline a lot simpler because you'd get the full path and not have to go digging

**Comment by EricZimmerman** [comment]
Look at a PowerShell example. Anything with the name of the exe in it would get flagged as being the path. I've seen cases where there are two of them. Which one do I pick?

**Comment by randomaccess3** [comment]
Anything that matches
Which as a rule will probably be fine...as opposed to saying it won't work because of the exception?

**Comment by EricZimmerman** [comment]
yes, id rather have you find the path and it be on you, than guess, and maybe be wrong

i also do not want to alter the output at this time without coordinating with 508 authors

**Comment by randomaccess3** [comment]
Yep that's fair. Can bring it up with them. 

In the timeline you have some logic to pull out the full path. So it's really just applying the same to the standard CSV output. 

The other request is adding another column to the timeline to include the item that was parsed to generate the entry. This will make further investigation easier. TLE could have this column set to hidden by default so it shouldn't affect 508 too greatly as by default it would be hidden.
