### ISSUE TITLE
Timeline Explorer: Error:Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Che4ter** [EricZimmerman/Issues#166]
Hello
I recently had to analyse a .csv report that contained very long log lines. When I tried to load them into Timeline Explorer it crashed with the following error message:
```
2021-03-10 11:37:59.4609 | INFO | Timeline Explorer v1.3.0.0 ready!
2021-03-10 11:38:15.0605 | INFO | Loading 'Y:\Tools\Index_error_example.csv'...
2021-03-10 11:38:15.5795 | ERROR | There was an error loading 'Y:\Tools\Index_error_example.csv'

Error:Index was outside the bounds of the array.
```
I tried to narrow the error down and it looks like it happens when you have a column containing "" and a length longer than about 2050 characters. Without the "" it works even with longer lines.

I've attached you my sample export. With this you should be able to reproduce the behaviour:
[Index_error_example.csv.txt](https://github.com/EricZimmerman/Issues/files/6115168/Index_error_example.csv.txt)

**Comment by EricZimmerman** [comment]
i would suggest getting the thing generating the report to not drop out extra empty quotes for no reason, but i cant replicate this.

i just updated to TLE latest this morning and loaded the file you shared. worked fine

![image](https://user-images.githubusercontent.com/4265254/110636741-9d4d1580-817a-11eb-82a7-5becb3f23fdf.png)

**Comment by Che4ter** [comment]
Originally the quoting coming from command line arguments. Very strange, but you are right. When I download the timeline explorer again it works. But with my current v1.3.0.0 version not. Anyway it's solved. Thanks for your support and sorry for the false issue.
