### ISSUE TITLE
ShellBagsExplorer MFT record number issue

### ISSUE THREAD

**Issue by rkeir** [EricZimmerman/Issues#169]
SBE seems to form an incorrect MFT record number in some cases. It may be related to the Sequence Number component of the raw value being **0xffff** since all seemingly incorrect cases I've seen have that in common.

From the raw BagMRU item having the stream of bytes **10 20 62 8D 82 81 FF FF**, this representing the 64 bit MFT value **0xffff81828d622010**, SBE reports a MFT record from that number of hex **00820F622010** and a sequence number of **ffff**. 

Surely the correct MFT record number in this case (the low 6 bytes) would be **81828D622010**?

Perhaps a sign extension issue or something?

**Comment by EricZimmerman** [comment]
probably. can you send me the hive in question? that is a very strange sequence number. it looks wrong.

is this on an NFTS file system vs FAT etc?

**Comment by EricZimmerman** [comment]
if you can also confirm, from the same system, what the actual FILE record looks like, that will he helpful too (assuming its NTFS of course)

**Comment by rkeir** [comment]
Unfortunately I can't send the full hive file. But this is what the BagMRU data looks like. Apologies for the formatting. 64 bit MFT value starts at offset 0x2E (10 20... FF FF). It's a regular type 0x30 FILE_ENTRY type. This is from an NTFS file system.

`BagMRU Item - 98 (0x62) bytes
           00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
           |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
00000000   60 00 31 00 40 00 00 00 5E 4F B5 8D 10 00 4E 65  `.1.@...^O....Ne
00000010   77 20 66 6F 6C 64 65 72 00 00 46 00 09 00 04 00  w folder..F.....
00000020   EF BE 5E 4F B5 8D 5E 4F B5 8D 2E 00 00 00 10 20  ..^O..^O....... 
00000030   62 8D 82 81 FF FF 00 00 00 00 00 00 00 00 00 00  b...............
00000040   00 00 00 00 00 00 00 00 4E 00 65 00 77 00 20 00  ........N.e.w. .
00000050   66 00 6F 00 6C 00 64 00 65 00 72 00 00 00 1A 00  f.o.l.d.e.r.....
00000060   00 00`

**Comment by EricZimmerman** [comment]
yea thats not helpful.

can you at least export out the raw bytes via Registry Explorer or something else so i can try to make sense of it? 

if not, not much i can do. this is the first i have seen this issue and that sequence number seems broken. 

what does the FILE record look like? dump it with mftecmd, i have never seen a seq # that high before (maxed out).

**Comment by rkeir** [comment]
Yes, sorry about the lack of detail and clarity. Unfortunately the hive file would probably be considered company confidential information and it's also located on a system I don't have direct access to so can't easily extract MFT data etc. Agreed, the sequence number is "odd" to say the least. I will try to replicate the issue on my own system and at least provide some additional insight if I discover anything.

Is it worth inspecting your code that separates the MFT record and sequence number from the original data? Perhaps hack it under a debugger with the byte sequence **10 20 62 8D 82 81 FF FF** and see what it spits out? Whether the originating data is "correct" is not so much my issue but that what I am seeing in my own shellbag parsing code matches with what is seen from SBE. For everything but these MFT values that have ffff sequence entries it does match.

**Comment by EricZimmerman** [comment]
unfortunately you will need the FILE record to validate this.

its not just taking 6 bytes and 2 bytes and calling it a day.

i worked with Dave Cowen on this way back in the day and the implementation can be seen here.

https://github.com/EricZimmerman/MFT/blob/master/MFT/Other/MftEntryInfo.cs#L7

this is why i asked what the FILE record looks like, so we can compare it there with MFTECmd, x-ways, tsk, etc.

**Comment by rkeir** [comment]
FWIW on my own system I do see a small number of ffff sequence number entries. They all appear to be related to stale paths referring to external drives that are no longer mounted (X:\blah, Y:\blah...). For these, in addition to the suspicious ffff sequence number, the MFT record number also seems bogus and not even in a range that I would even consider valid. In fact what would an MFT record number even mean for a file on an external network share like these? It's like fff really means "_the MFT data is not relevant here_".

**Comment by EricZimmerman** [comment]
there is some built in logic to look at entry and seq nums to determine if its ntfs, etc. i would think for a unc it should not be treated as an MFT entry info and probably more like FAT? i havent looked at those specifically to see if what comes across in a while for unc or mapped share values.

strange indeed and it may end up just being one of the dark corners of shellbags

**Comment by rkeir** [comment]
I'm not a C# developer but I believe there's a few things wrong with that code up there.

uint entryIndex; --> ulong entryIndex;
uint entryIndex2 --> ulong entryIndex2
entryIndex2 = entryIndex2 * 16777216; //2^24 --> entryIndex2 = entryIndex2 * 4294967296; //2^32

**Comment by EricZimmerman** [comment]
well its been right for every use case i have seen in shell bags and the MFT, so not sure what you mean.

ill see if dave can chime in. 

totally happy to fix it if there is an issue, not saying that, but i need more info and a test case where its wrong to see it happen and NOT match other tools, the MFT, etc

**Comment by EricZimmerman** [comment]
if you are not 100% sure that the file systems in question are NTFS, then the MFT stuff is NOT going to be related to entry and sequence number. rather, it would be an offset to a directory entry etc (for fat, etc).

see the manual for more i believe, but if you are looking at unc or external NON ntfs volumes, the rules change

**Comment by EricZimmerman** [comment]
more than likely, the 2^24 was the old value i was using, and i commented it out, replacing it with 16777216.

**Comment by rkeir** [comment]
Hi Eric, sorry to prolong this. I'm pretty sure the issue has gone unnoticed since typically the MFT record number will only occupy 4 bytes. In these odd cases with bogus numbers, they're taking up all 6 bytes and seems to have revealed a couple of issues to do with overflowing 4 and 2 byte integers, with bytes being shifted away at the top end and incorrect merging of the two values as a result.

I've replicated it in a C# playground site. Hit Run for each of these so you can see the output and intermediate results. For all cases I'm using my actual 8 byte raw MFT number as given by the stream of bytes { 0x10, 0x20, 0x62, 0x8d, 0x82, 0x81, 0xff, 0xff }. The correct result for this should be an entry index of 0x81828d622010.


Here's essentially the original code:

https://dotnetfiddle.net/ph4hmF


This one is my changes to the type of variables and the bit shift calculation:

https://dotnetfiddle.net/Jk8Yxn


This final one is simplified by using a 64 bit type for the index number. To be honest I'm not quite clear why the original wanted to break things into 2 parts of smaller types to calculate and re-form the entry index:

https://dotnetfiddle.net/ft71S6

**Comment by EricZimmerman** [comment]
thanks, ill take a look.

i assume that the "should be" values for entry and seq come from the actual FILE record itself? what do other tools show for the entry and seq # 

i would like to see how tsk and x-ways reports those values too

**Comment by rkeir** [comment]
The "_should be_" values are simply what the extracted MFT record number should be, given the sequence of 8 bytes the code is looking at. It doesn't matter where those bytes came from or what they represent. The code as is stands doesn't correctly extract the 6 byte MFT file record component from those 8 bytes.

**Comment by EricZimmerman** [comment]
i think there is more to it than this. 

its a 48 bit number for the entry #, and 16 bit for sequence.

in a FILE record you often see

00 00 C3 04 04 00

which would be 0x 0404C3 for entry # 

in a shell item and index record, things change like this:

C3 04 04 00 00 00 01 00

where seq would be 1 and entry would still be 0404c3

this code

```
 var rawEntryBytes = new byte[] { 0x10, 0x20, 0x62, 0x8d, 0x82, 0x81, 0xff, 0xff };
		
	uint hi = BitConverter.ToUInt16(rawEntryBytes, 0);
	  ulong low = BitConverter.ToUInt32(rawEntryBytes, 2);
	  
	  Console.WriteLine("hi " + " d " + hi + " h " + hi.ToString("X"));
	  Console.WriteLine("low " + " d " + low + " h " + low.ToString("X"));
	  
	  long lhi = (long)hi;
	  long llow = (long)low;
	  	  
	  var sss = (lhi << 32) | llow;
	  
	  Console.WriteLine("sss" + " s " + sss + " x " +  sss.ToString("X"));
```
correctly deals with what you would find in a FILE record

next I want to tweak that code to handle the shellitem and index case, to see if it matters.

see here

https://github.com/libyal/libfsntfs/blob/main/documentation/New%20Technologies%20File%20System%20(NTFS).asciidoc#53-the-file-reference

and that it is just saying its only 32 bit in size, so would that just be the first 4 bytes, ignoring the next 2, then taking the last 2 as seq #? maybe, maybe not.

this is why we really need even a single FILE record that corresponds with a folder in a shell item, so we can see how its stored in the MFT vs shell item

if you have the MFTs for those drives, or can reproduce this, you can use MFTECmd to extract out a single file record to a binary file which we can then look at in more detail.

i dont want to assume anything here in how the data is stored, so we really need to track down some valid test data from an MFT, the corresponding shell item in shellbags (ie the beef004 extension block) so we can see how things line up.

ideally you would also be able to track down the corresponding $I30 file so we can look at that too and see how the data is stored there.

when i look at MFT references in an index, its the same as i see in shell items (ex. C3 04 04 00 00 00 01 00), at least for "normal" looking ones

we can figure this out rather quickly i think, but that test data is key

**Comment by rkeir** [comment]
Yes, the whole MFT file ref thing is 64 bits (8 bytes) as you say, with 2 bytes for the sequence number and 6 bytes for the record number. However, as you also pointed out, the actual usage of the record number is as a 32 bit (4 byte) value in the MFT. I'd always been puzzled by that _wasted_ extra 2 bytes. And yet we do see it being used in some form here with shellbags. However, most likely in these shellbag special cases the presented number has nothing to do with actual MFT values (e.g. the target is referencing file shares) and are kind of invalid.

The code you had to handle the MFT values in shellbags was thrown off by these values that occupied >4 bytes (top 2 bytes were non-zero) and reported incorrect results, but would have worked in the 99.9% of cases where these MFT values were only occupying 4 bytes (top 2 bytes were zero). That was really my only issue.

I will do some digging and see how the FILE record details match up with the shellbag MFT details and report back when I get a chance.

**Comment by EricZimmerman** [comment]
sounds good. FFFF is not a valid value for a sequence number, so this must be something else. a dark shellbags corner. i have some feelers out with people seeing if i can track down more details.

the hex is always there in SBE for this reason

will close for now until we get more info

**Comment by rkeir** [comment]
For validation -- I have a directory entry reported from shellbag parsing. It's full path is **C:\Temp\Example**. It is a live and still present directory on my drive (NTFS).

The raw bytes of the shell item from the registry for the **Example** entry show the 8 byte sequence for the MFT file ref as

1A 06 00 00 00 00 DC 01

This is interpreted (by my code) as 

  MFT Entry : 1562 (0x061A)
  MFT Seq   : 476  (0x01DC)

Visiting this MFT record number (1562) I see that it is indeed the **Example** directory record.

Since MFT FILE records do not themselves contain a field for their own record number I need to go down one level inside the **Example** directory to find a file that references its parent record. Such a reference can be found in the FILE_NAME attribute section with the parent directory file record field.

So I find the FILE record for e.g. **C:\Temp\Example\test.txt**

In its FILE_NAME attribute section, the parent directory file record number and seq number is seen as the sequence of 8 bytes of

1A 06 00 00 00 00 DC 01

i.e. identical to how the shellbag refers to that item.

It's my conclusion therefore that for "valid" MFT file references, shellbag stores the same information in the same format and same size as seen on disk in the MFT.
