### ISSUE TITLE
TLE: Dragging columns

### ISSUE THREAD

**Issue by b1draper** [EricZimmerman/Issues#171]
Yesterday I'd watched the event log Webinar demo where TLE was used for viewing the !EZParser eventlog timeline with grouping the column headers. I was messing around with grouping different headers. I grabbed a header and drug it up to where an "x" was displayed now TLE no longer displays that column of data. Is there a way to reset TLE to bring the missing headers back? When I open the CSV in Excel the column is still there.

https://urldefense.us/v3/__https:/global.gotowebinar.com/join/6577596729092558349/296740681?utm_campaign=NA-CY-CT-TY-CP-NN-NOTAV-NAEVT2103ELQ*2BEvtxECmd*2BKAPE&elqid=CDUFF000001385489&utm_medium=email&utm_source=Eloqua__;JSU!!BClRuOV5cvtbuNI!W-exk5u5BbP1MewHFy0d40E4PcZVgchXa4HiGCpbawNUlTw4nRnzaesLM9GtJmfG5ffEWQ$

**Comment by AndrewRathbun** [comment]
Hey there, this is Andrew from the Webinar. Give me a second and I'll show you what you have to do.

**Comment by AndrewRathbun** [comment]
![537kMyYHbP](https://user-images.githubusercontent.com/36825567/113346409-d011a600-9301-11eb-9642-cb47bf71afd1.gif)

**Comment by EricZimmerman** [comment]
easy!

**Comment by b1draper** [comment]
Wow, thanks for the quick response. BTW, what app are you using to create the animated GIF screen capture so quick?

**Comment by AndrewRathbun** [comment]
ShareX. Free and open source!
