### ISSUE TITLE
RECMD - SAM Plugin

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#172]
It looks like the SAM plugin only presents the data from the F and V values

![image](https://user-images.githubusercontent.com/1241363/113534415-0f970580-9614-11eb-990a-54d80e6a19db.png)

There's some useful information in the other values if a Microsoft account is connected that would be good to have in the SAM Plugin output.
I think the InternetUserName value is the most important one to have because that'll give the email.

**Comment by EricZimmerman** [comment]
do you have a hive with this data in it so i can update the plugin?

**Comment by randomaccess3** [comment]
Yep. Can send tomorrow. Otherwise both Blake and rocba have it.

**Comment by EricZimmerman** [comment]
yea if you can shoot out one of those sam hives that would be enough

**Comment by EricZimmerman** [comment]
![image](https://user-images.githubusercontent.com/4265254/114435682-6f505c00-9b92-11eb-95e6-e5a4dd4735fb.png)

this is done
