### ISSUE TITLE
RLA - additional flag

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#174]
Would be great if RLA had a flag that allows to copy the registry hive even if the log doesnt need to be applied.

**Comment by EricZimmerman** [comment]
Why though? You don't need to copy anything because the hive doesn't need repaired so just take the original Hive and off you go

Unless I'm missing something?

**Comment by randomaccess3** [comment]
Centralise all hives with the naming format RLA uses into one directory. 

Makes it easy to create a session and load it into RE and then not have to worry about reloading logs each time.

**Comment by EricZimmerman** [comment]
so you want this to save the non dirty hive to the output dir like it would if there was logs to replay, right?

**Comment by randomaccess3** [comment]
Yep
Ultimately you'd have the single dir that has all the hives in their most up to date state.

**Comment by EricZimmerman** [comment]
im confused. there is already an option for this...

```
 _fluentCommandLineParser.Setup(arg => arg.CopyAlways)
                .As("ca")
                .WithDescription(
                    "When true, always copy hives to --out directory, even if they aren't dirty. Default is TRUE").SetDefault(true);
```

did you try this?

**Comment by EricZimmerman** [comment]
```
  if (logFiles.Length == 0)
                        {
                            if (_fluentCommandLineParser.Object.CopyAlways)
                            {
                                _logger.Info($"\tHive '{hiveToProcess}' is dirty, but no logs were found in the same directory. --ca is true. Copying...");
                                updatedBytes = File.ReadAllBytes(hiveToProcess);
                            }
                            else
                            {
                                _logger.Info($"\tHive '{hiveToProcess}' is dirty and no transaction logs were found in the same directory. --ca is false. Skipping...");
                                continue;    
                            }
                        }
```

**Comment by randomaccess3** [comment]
im blind apparently. I could have sworn it didnt have a flag, but clearly I was wrong. Sorry!
