### ISSUE TITLE
ShellBags Explorer Load Active Registry

### ISSUE THREAD

**Issue by chadtilbury** [EricZimmerman/Issues#176]
ShellBags Explorer and SBECmd will miss data with the "Load Active Registry" feature if not run with administrator privileges.  "Has Explored" data and in some cases First/Last Explored times may be missing.  Recommend adding a warning to run as administrator and/or request elevated privileges (GUI). 

It would also be worth adding a notice for this feature that ShellBags Explorer is only parsing UsrClass.dat and may be missing data present in the live user's NTUSER.DAT hive.

**Comment by EricZimmerman** [comment]
SBE and SBECmd already do that and have forever:

![image](https://user-images.githubusercontent.com/4265254/148128888-24d4ae1c-de54-4567-a7ed-ae601a1dcc46.png)

![image](https://user-images.githubusercontent.com/4265254/148128965-26b059c3-2bc6-4a67-a33b-c93bc1d1a41b.png)

in my experience, if there is data in usrclass.dat, there is none in ntuser.dat

do you have hives where this is not true?

**Comment by EricZimmerman** [comment]
as to the notice re NTUSER, this is more of an RTFM/understanding the artifact vs something the tool should be telling the user (i.e. PLEASE ALSO LOAD NTUSER.DAT) kind of thing

if i am misunderstanding this we can reopen, but the warnings have always been there
