### ISSUE TITLE
RECmd:  Issues processing a directory with "clean" hives

### ISSUE THREAD

**Issue by timtaylor3** [EricZimmerman/Issues#179]
I use rla.exe to process all registry hives into a single directory and then point RECmd at that directory using "-d".  This worked under the older versions of RECmd.  I'm not sure if this is an issue or not but  now when I use "-d" to process a directory with clean hives, RECmd does not find any hives.  

Processing a normal directory structure works fine as expected.

"-f" works as expected on the cleaned files.

**Comment by AndrewRathbun** [comment]
Can you post the command you're using as well as the output using `--debug`?

**Comment by AndrewRathbun** [comment]
Also, check here regarding the `--nl false` flag in RECmd to automatically replay transaction logs - https://github.com/EricZimmerman/KapeFiles/blob/7994aafc622ce7f450863951a76a55bfe39cc799/Modules/EZTools/RECmd/RECmd_Kroll.mkape#L11

**Comment by EricZimmerman** [comment]
I think this is more related to the fact that it can't find the high files to process based on the names. Can you Post a list of all the file names in the directory that you're trying to have RECMD process as I just need to update the matching rules I think in d mode

**Comment by timtaylor3** [comment]
Ah, the --nl log should mean I don't need to run rla first.  

PS C:\Users\ttaylor> E:\Projects\Triage-dev\ztools\net6\RECmd.exe -d C:\cases\ez-tool\cleaned_registry\REDACTED --csv C:\cases\RECmd_Test --bn E:\Projects\Triage-dev\config_data\reb\All.reb  --debug
[2022-01-29 09:56:03.0833443 INF] RECmd version 2.0.0.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/RECmd

Note: Enclose all strings containing spaces (and all RegEx) with double quotes

[2022-01-29 09:56:03.1080788 INF] Command line: -d C:\cases\ez-tool\cleaned_registry\REDACTED --csv C:\cases\RECmd_Test --bn E:\Projects\Triage-dev\config_data\reb\All.reb --debug


[2022-01-29 09:56:03.4843441 INF] Total hives found: 0
[2022-01-29 09:56:03.4880918 WRN] No hives were found. Exiting...

**Comment by EricZimmerman** [comment]
RLA is a good thing to run, especially if the hives are dirty. So you're doing the right thing, but if you did not have the transaction logs then NL at least gives you a way around that

**Comment by timtaylor3** [comment]
The output file names all end with the hive name, like _UsrClass.dat, _SAM etc.  Nothing was changed on my end with the change to the net6 version.

**Comment by timtaylor3** [comment]
this is the rla command I use if it helps:  rla.exe -d "input_path" --out "clean_registry_dir" --ca True --cn False

**Comment by EricZimmerman** [comment]
ok ill check the globs

**Comment by EricZimmerman** [comment]
update posted. check for updates or redownload from my main site, then try again.

**Comment by timtaylor3** [comment]
That did the trick.  Thank you.  It is working as expected.

**Comment by EricZimmerman** [comment]
Sweet
