### ISSUE TITLE
Timeline explorer import issue 

### ISSUE THREAD

**Issue by ToomsDK** [EricZimmerman/Issues#18]
[recovered-pf-analysis.zip](https://github.com/EricZimmerman/Issues/files/2138815/recovered-pf-analysis.zip)

Timeline explorer import issue 
Windows 7 with Danish locale

**Comment by EricZimmerman** [comment]
no bug that i can see. a few things

1. file didnt have headers. 
2. the file used unix line separators vs CRLF

when i added headers and changed it to CRLF, i got this:

![image](https://user-images.githubusercontent.com/4265254/41937217-bd2660aa-795d-11e8-84eb-afa2efeb98b3.png)

and dragging it in, i got this

![image](https://user-images.githubusercontent.com/4265254/41937223-c09a8ae0-795d-11e8-9a4f-49ea1283c4db.png)

**Comment by ToomsDK** [comment]
i was just following the SAN for508 exercise 3.1 page 15 and when i load the .csv file it is looking like the screendump include.
Agree that it is up to you to define if this is an bug or not, but when i load the file then i dont see the result that you do and yes there is no headers but even then it seems to load it all in one line.

Can the app not just check if it is LF or CRLF and then load based on that and if there is no headers like in this sample then maybe just make them up like COL1, COL2 and so on... and then give the option to modify the names after load.

Thanks 
Thomas

**Comment by EricZimmerman** [comment]
not much i can do here, at least in regard to the file missing headers.

the thing is, how would i know there arent any headers?

The next version will include the ability to automatically detect line feed type tho.

**Comment by syedhnaqvi** [comment]
Hye,
Whenever i try open csv file into time line explorer seeing this issue . Plugins are these in associated directory. 
2022-07-26 23:06:36.9669 | INFO | Loading 'C:\Windows\Prefetch\ACROBAT.EXE-4E1700B6.pf'...
2022-07-26 23:06:37.2483 | WARN | No plugin for generic CSV/TSV files found. aborting

**Comment by EricZimmerman** [comment]
Did you unzip with windows? If so all the ddls are blocked.
