### ISSUE TITLE
Timeline Explorer DotNet 4 Update

### ISSUE THREAD

**Issue by Xboarder56** [EricZimmerman/Issues#181]
Hi Eric, 

Was wondering if there was a chance to have Timeline Explorer DotNet 4.X upgraded to 2.0.0.0 like the 6.X branch? Running this under wine and I'm forced to use the DotNet 4.X version

**Comment by EricZimmerman** [comment]
No. There will never be updates to the legacy guis.as I start using more net 6bsorcifoc stuff that would quickly become untenable

Why not qemu +virt manager vs wine?

**Comment by Xboarder56** [comment]
Gotcha thanks for the quick response. Running it via sift on aws.
