### ISSUE TITLE
Label tool output to include which VSS was parsed

### ISSUE THREAD

**Issue by salty4n6** [EricZimmerman/Issues#182]
Hi,
Is it possible to include which VSS the output data corresponds to?  For example, on my test system I have 4 VSCs and this is how the files are named when parsing all collected data, including the 4 VSCs.

![image](https://user-images.githubusercontent.com/81833785/157500259-c0eb4c14-0c58-4113-b532-dbb9dbe986a3.png)

Truly appreciate the time and effort you've put into these tools.  Great work!

Thanks,
Salty

**Comment by EricZimmerman** [comment]
the console would have that detail, but can you check inside the csv itself to see if there is a SourcePath?

**Comment by salty4n6** [comment]
I know the console output has that detail but this was an ask in terms of efficiency.  Sorry I should have clarified.  I didn't see the source path in the example I posted.  I double checked before thinking that might be the case.

**Comment by EricZimmerman** [comment]
how are you running amcacheparser in this case? amcacheparser does not have an option --vss to parse everything from a shadow copy.

**Comment by salty4n6** [comment]
I'm using Kape to gather and parse the collected data.

![image](https://user-images.githubusercontent.com/81833785/157505487-33bb30e5-57c2-43ad-9ec5-04db805aca86.png)

**Comment by EricZimmerman** [comment]
in that case i would refer to the ConsoleLog as needed once you find something of interest in the amcache csvs.

the only other option would be me adding a SourceFile column thats super redundant for every row

**Comment by salty4n6** [comment]
Totally understand about adding a column and it being redundant, completely agree.  I was just thinking about within the file name but your suggestion sounds like the best solution.   Thank you.

**Comment by EricZimmerman** [comment]
sure thing! i would think that finding an of interest item would be first, then, if needed, you can back into where it came from from the consolelog.
