### ISSUE TITLE
SBECmd not processing cleaned hives

### ISSUE THREAD

**Issue by timtaylor3** [EricZimmerman/Issues#184]
This issue is similar to the previous issue I reported with RECmd.  RLA is used to process all hives into a single directory for processing.  SBECmd fails to find usrclass.dat.  Works fine when processing in the native location.

**Comment by timtaylor3** [comment]
Please hold for that issue. I could be in error.

**Comment by timtaylor3** [comment]
The net4 version works fine.  I did confirm the issues is only in the net6 version.  I believe your fix for RECmd had to do with the "globing" of the files.

**Comment by EricZimmerman** [comment]
should be fixed. please update and try again.
