### ISSUE TITLE
Please tell Registry Explorer users why "File > Live system" is unusable if they're not an administrator

### ISSUE THREAD

**Issue by unforgettableid** [EricZimmerman/Issues#186]
Many users fail to read instructions.  I failed to read them, too.

# Steps to reproduce

* Download Registry Explorer
* Don't read any instructions
* Unzip the zip file into a subfolder of your Downloads folder
* Run it for the first time, to try it out and see if you like it
* Open the File menu

# Observed

* "File > Live system" is grayed out, for no obvious reason.

# My suggestion

If you run Registry Explorer as a limited user, please make "File > Live system" clickable instead of grayed out.  If you click it, it could show a message box with the following message:

# Suggested message-box text

To load Registry hives from the live system, you must run Registry Explorer as an administrator.  Please quit, then right-click on the Registry Explorer icon, then choose "More", then choose "Run as administrator".

**Comment by EricZimmerman** [comment]
Nah. Rtfm
