### ISSUE TITLE
EvtxECmd Parsing issues with Powershell 400 and 600 events

### ISSUE THREAD

**Issue by jball77-git** [EricZimmerman/Issues#189]
Recommended to create an issue from DFIR Discord channel.  I have discussed this with the community and not sure how to proceed or if this is an edge case. I am getting strange output (See attached images) from EvtxECmd and I'm not sure what else I can do to fix this in the future.  

![image](https://user-images.githubusercontent.com/95216754/179926549-0f33afc4-df3b-47fc-9302-9a5d8f62d557.png)

How to replicate issue:

- Mount the DFIRMadness DC01 Image with Arsenal Image Mounter.  Added Evtx dir so you don't need the full image.
- Run 'EvtxECmd.exe  -d D:/path/to/evtx/files -csv C:/wherever' (No errors)
- View csv in TLE and any text editor, see lines after 85229.  In TLE, filter for 400 and 600 events and Powershell for the provider.

Looking at those event maps, I think the issue is that these logs don't have "HostApplication" values and I am not sure how to properly parse these, or when changes to these events were made.  I have tried to change the order of the Properties parsed in the map file, but had the same outcome.  I also don't know how to exclude a single provider (Windows Powershell) in an automated way. While I can exclude 400 and 600 events, this will also overlap with "Microsoft-Windows-Kernel-PnP" and "Microsoft-Windows-TaskScheduler", which I would prefer not to do.  

![image](https://user-images.githubusercontent.com/95216754/179926383-a482d65d-582d-497a-9713-7110ed6cfa79.png)
![image](https://user-images.githubusercontent.com/95216754/179928834-9fbabe35-6676-4e4e-bdfb-ca9cb22d7cf2.png)

Please let me know if I am doing something wrong or if I can provide other useful information.  
Evtx directory from DC01: [logs.zip](https://github.com/EricZimmerman/Issues/files/9147625/logs.zip)

**Comment by AndrewRathbun** [comment]
I'll take a look at this in a few. Guessing the regex needs to be adjusted.

**Comment by AndrewRathbun** [comment]
I just did a test on the PowerShell logs on my own system and got the following results:

![image](https://user-images.githubusercontent.com/36825567/180019231-47649982-48e5-4b48-8009-319ca35faf11.png)

I wonder if, for whatever reason, the HostApplication wasn't being recorded, wasn't enabled, or another reason on that particular system (DC01)? I don't really have an explanation but the EvtxECmd Map seems to be functioning correctly so long as the data exists.

Let me know if you need anything else @jball77-git
