### ISSUE TITLE
TimelineExplorer:  Error reading the output file of analyzeMFT

### ISSUE THREAD

**Issue by hyuunnn** [EricZimmerman/Issues#191]
I have uploaded a image of the error and the file in problem.
![image](https://user-images.githubusercontent.com/15611739/183299525-9c173f14-0c8d-435a-91dc-16aaa5b9544b.png)
[test1.csv](https://github.com/EricZimmerman/Issues/files/9277088/test1.csv)

**Comment by EricZimmerman** [comment]
I do not recommend using analyzemft. 

It's slow and wrong in many different ways, at least in regard to being a file analysis tool. Analyzemft is more of an MFT dumper than anything else
