### ISSUE TITLE
TLE - GUI QoL Request 

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#193]
Hey!
Would be great to have a few extra options in the view settings for TLE
* Word wrap on cells (maybe a right click menu item on a specific cell - otherwise some items will make the view untenable)
* Max column width
* Set all columns to x width
* Set column to x width (right click on column header)

Sometimes the "best fit" messes things up and you end up with a massively long row because some of the columns have super long items in them.

Any consideration is appreciated :) thanks!

**Comment by EricZimmerman** [comment]
There's already an option that does all that. Under tools

Reset column widths or similar

It was added for the reasons you mention above.

**Comment by randomaccess3** [comment]
Will test it again tomorrow but think I did that and it didn't help on this custom csv

**Comment by randomaccess3** [comment]
ok! so the reset column widths works provided you want to change the width of everything back to something manageable.

Would be good to have a right click for wrap (or global, but that's dangerous) and set column width (right click on column header) still. Especially when working on laptop screens!

**Comment by EricZimmerman** [comment]
for supported file types, col widths are remembered. for others, the existing resize gets you there. the other stuff is not available that i see, vs what is already on the context menus of the grid.

**Comment by randomaccess3** [comment]
Word wrap on cells as an option would be a great improvement. 
The others are pretty much satisfied by ctrl+r. 

But wordwrap would be great to toggle on and off for a cell
