### ISSUE TITLE
TLE: Columns imported from CSV with 3 capital letters [A-Z] do not appear in GUI

### ISSUE THREAD

**Issue by crash0ver1d3** [EricZimmerman/Issues#195]
In Timeline Explorer (TLE) v2.0.0.1, importing a csv file of Linux System activity containing values "Date, Size, Type, Mode, UID, GID, Meta, File Name", results in the columns, "UID and GID" to not appear in the TLE graphical user interface (GUI).

By adding a lowercase 's' to "UID and GID", thus changing the column names to "UIDs and GIDs", TLE was able to 'see' the columns and properly render them in the GUI. Additionally, by adding an uppercase 'S' to the column names, creating "UIDS and GIDS", TLE was able to import those properly.

Another test that I performed, was to change the column headers to their original values, but in lowercase text, creating "uid and gid". Importing the CSV with the lowercase column names consisting of three letters [a-z], caused TLE to throw an error and not render any of the data in the CSV file.

I have provided screenshots and the CSV file that contains the original column names, "UID and GID", to allow for proper test. The CSV file is from a training class and does not contain sensitive information or PII.

<img width="1080" alt="Timeline_Values" src="https://user-images.githubusercontent.com/39965542/211181025-30147103-8fdd-449a-8103-e82637ddfc2e.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/39965542/211181085-a29a22af-05c5-48ef-be66-59ba9c74a0d8.png">

<img width="952" alt="TimelineExplorer_lowercase_uid_gid_error" src="https://user-images.githubusercontent.com/39965542/211181048-2147aeed-0135-4f16-a478-02659eea3fb0.png">

[timeline.csv](https://github.com/EricZimmerman/Issues/files/10367750/timeline.csv)

**Comment by EricZimmerman** [comment]
what generated this file? looks like mactime. those columns are probably just hidden. right click on any column header, column chooser, then add them back.

you can also look at the messages and it will tell you what kind of file TLE thinks it is when its being loaded

the column IS there, its just hidden by default

**Comment by EricZimmerman** [comment]
if thats not the case, share the csv in its original file and we can go from there

**Comment by crash0ver1d3** [comment]
Thanks for taking a look.

this file was generated from a bodyfile of linux file system activity.

The CSV is shared, timeline.csv, at the bottom of the last screenshot.

Column chooser did show the columns to add back.

Why would UId and GId be hidden by default, but when adding any letter after the UId and GId would the columns be displayed by default?

Sharing CSV file again here for ease of identification.

[timeline.csv](https://github.com/EricZimmerman/Issues/files/10374375/timeline.csv)

**Comment by EricZimmerman** [comment]
Because body file is a recognized file format and the one that you changed when you added numbers or letters to the end made it not natively supported which then use the generic CSV plugin to load it

You can see all of this activity. If you bring up the messages tab, it will tell you exactly what kind of file timeline explorer thinks it is
