### ISSUE TITLE
LECmd encoding issue in csv output file

### ISSUE THREAD

**Issue by RevD17** [EricZimmerman/Issues#198]
Ran into a problem with parsing lnk-files with cyrillic symbols by LECmd, version 1.5.0.0.
When running LECmd with --csv argument on lnk file containing in name or filepath cyrillic symbols, geting path values like this:
"My Computer\E:\РђС‚С‚РµСЃС‚Р°С†РёСЏ" in programs like CSVFileView, i.e. all text in ASCII code page except name that is in UTF-8.

In hex view:    45 3A 5C D0 90 D1 82 D1 82 D0 B5 D1 81 D1 82 D0 B0 D1 86 D0 B8 D1 8F (ASCII + UTF-8)
In text view:   E:\РђС‚С‚РµСЃС‚Р°С†РёСЏ
Original view: E:\Аттестация

But Notepad++ reads this file well.
As i can see, cyrillic lnk-files contain file names both in UTF-16be and Windows CP1251.

Original view:   E:\Аттестация
Inside lnk hex view 1: 45 3A 5C C0 F2 F2 E5 F1 F2 E0 F6 E8 FF (ASCII CP1251)
Inside lnk hex view 2: 00 10 04 42 04 42 04 35 04 41 04 42 04 30 04 46 04 38 04 42 (UTF-16be, i don't know what happend with first character)

I can give you examples of such files, if you needed.
Thank you!

**Comment by EricZimmerman** [comment]
So does the actual name of the link file itself contains cyrilic characters? Or is it extracting out Cyrillic characters inside of the link file as it's being parked?

Sample files are always appreciated because then I can test it live to make sure we get it handled

**Comment by RevD17** [comment]
All of the above.
Attachment is 7z archive with lnk files inside.
[Examples.7z.zip](https://github.com/EricZimmerman/Issues/files/10558218/Examples.7z.zip)

**Comment by RevD17** [comment]
I found some new details:
In RelativePath and TargetIDAbsolutePath columns of output LECmd csv file cyrillic symbols are in UTF8,
in LocalPath and CommonPath columns cyrillic symbols in unknown (for me) encoding type like UTF16, for example:
Text: "АБВГД"
UTF8: D0 91 D0 92 D0 93 D0 94 D0 95 
UTF16: 04 10 04 11 04 12 04 13 04 14
"Unknown" wide: C3 80 C3 81 C3 82 C3 83 C3 84
For now, i have parsed csv file and in LocalPath and CommonPath columns for "unknown" encoding symbols just skipping first byte 0xC3 and adding 0x40 to code of second byte. Result codes are in cp1251.

**Comment by EricZimmerman** [comment]
looking into this now

**Comment by EricZimmerman** [comment]
hmm, if you change your codepage to cp1251 does it display properly? this is a tough one.

i just dont know how i would be able to programmatically encode the string in only those situations as 1251

**Comment by EricZimmerman** [comment]
in my IDE i see this for the short name:

Тамбов.xlsx
Владимир.xlsx\u0000

which seems to boil down to the code page displaying the data?

**Comment by EricZimmerman** [comment]
ill see what i can do with this, but will close for now. right now i have it set to invariant culture when generating the csv. might be able to set current culture

**Comment by RevD17** [comment]
> in my IDE i see this for the short name:
> 
> Тамбов.xlsx Владимир.xlsx\u0000
> 
> which seems to boil down to the code page displaying the data?

It looks like some "smart" programs like Notepad++ or VSCode can boil down "unknown" symbols in a different encoding inside file and display it correctly, that is RelativePath and TargetIDAbsolutePath which in UTF-8, but isn't in LocalPath and CommonPath fields.
Changing displaying code page to cp1251 doesn't help cause cyrillic names are still in other encodings.
For now, i still will parse csv output file. Sometimes Windows does some "magic" using different encodings.
We'll see, may be invariant culture helps.
Thank you very much!
