### ISSUE TITLE
Shell item parser missing data sometimes

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#199]
Have noticed that the AbsolutePath in various shell items has been missing data:

![image](https://user-images.githubusercontent.com/1241363/218600467-249dd829-10c1-4daf-90c5-9e1c2ac61101.png)

This is output from recmd for comdlg
If i open the same in Registry Explorer it shows the path properly

I've noticed this in JLECMD and LECMD as well.
Havent had a chance to recreate it with test data yet.

**Comment by EricZimmerman** [comment]
this is fixed. someone did a PR and messed up one of the checks. redownload and things will be working properly

**Comment by randomaccess3** [comment]
I updated everything and doesnt seem to have fixed it
Not 100% sure the latest versions on the site are the latest versions - lecmd commit date was june 2022?

**Comment by EricZimmerman** [comment]
What tool?

Recmd and re were updated.

**Comment by randomaccess3** [comment]
Ah ok. Haven't checked recmd. 
Same issues was seen in lecmd and jlecmd when I tested last week.

**Comment by EricZimmerman** [comment]
lecmd updated. adding new stuff to jumplists so that will have another update here soon.

jlecmd updated for now, as is jumplist explorer
