### ISSUE TITLE
Timeline Explorer Plugin Error

### ISSUE THREAD

**Issue by Luke-G-arcia** [EricZimmerman/Issues#200]
![TimelineErrors](https://user-images.githubusercontent.com/125694930/219771804-23e5c33e-4e6a-417f-b597-b160bbdc2fb2.PNG)

I am currently going though the GCFA course, so I am new to these tools and may be asking a dumb question here. I am getting an error where the exe can't find or use the associated DLLs, even though they are definitely still in the original relative location as downloaded from your GitHub. 

I've copied, reset the run as executable path, and still replicated this error from multiple directories. Is there something I am missing?

Thank you for your time and help. Big Fan.

-Luke

**Comment by EricZimmerman** [comment]
why is tle in that folder? how did you unzip it? with windows? if so all 
the dlls are blocked.

Delete TLe directory, reextract to say, C:\Tools\TLE, using 7Zip and 
things will be fine.

windows unzip blocks the DLLs and this is what ends up happening

**Comment by EricZimmerman** [comment]
if thats not it we can reopen
