### ISSUE TITLE
CDBurn ShellType

### ISSUE THREAD

**Issue by josejlpez** [EricZimmerman/Issues#201]
I am not able to find info in depth about CDBurn ShellType in ShellBags Explorer. My question is, when a folder is tagged as CDBurn ShellType?

I appreciate your answer in advance

**Comment by josejlpez** [comment]
I suppose it is related to the CD Burning Area of Windows Explorer or CDBurn Shell e.g. in Windows 7, but I don´t know for sure. And, what about third party CD Burning tools?

**Comment by EricZimmerman** [comment]
I found it in my work back in the day and reversed it. It happens with optical disks from what I recall. 

It's built into windows vs a third party tool.
