### ISSUE TITLE
[Suggestion] %d and %m KAPE variables parsing in SFTP destination path

### ISSUE THREAD

**Issue by reversebrain** [EricZimmerman/Issues#202]
When KAPE is configured with Targets and Modules enabled, it will push via SFTP two directories, one containing artifacts and one containing modules output. It would be great to have %d and %m variables parsing in SFTP destination path (--scd) in order to create one single directory where all files will be stored and to avoid creating a different command line for each compromised system

**Comment by EricZimmerman** [comment]
Use those variables in the base name for a zip file or vhdx. Then the variable expansion gets used in the filenames

You don't need a special command line per system
