### ISSUE TITLE
Unable to Load Workstation SYSTEM Hive

### ISSUE THREAD

**Issue by grook14** [EricZimmerman/Issues#205]
Attempting to load a SYSTEM hive in an investigation and I get the following error:

[SYSTEM_Hive_ERROR.txt](https://github.com/EricZimmerman/Issues/files/11793534/SYSTEM_Hive_ERROR.txt)

I wondered if I had corrupted something in transferring these hives, but I was able to load the NTUSER.DAT hive from the same system. I also tried loading the SYSTEM hive by itself as well as loading it _with_ the transaction logs added. No luck on that either.

Hope that is enough info. Thank you for your time!

**Comment by EricZimmerman** [comment]
Sure looks like corruption somewhere. 

Is this with the latest software?

**Comment by grook14** [comment]
Yes, v2.0.0.0

**Comment by EricZimmerman** [comment]
It happens. Not much you can do about it tho except try to manually repair things but that's a bit of work

**Comment by AndrewRathbun** [comment]
How were the hives acquired? With which tool? Or is this a live system? If it's a live system, do you get the same issue when you run Registry Explorer as Admin and loading the live hives?

**Comment by grook14** [comment]
Roger that. Thank you @EricZimmerman !
@AndrewRathbun - I obtained these hives via KAPE.

**Comment by EricZimmerman** [comment]
it happens. just saw this in the 498 VM. some goofy error when kevin tried it, works fine in my same VM.
