### ISSUE TITLE
EricZimmerman tools in SIFTVM

### ISSUE THREAD

**Issue by WW0nka** [EricZimmerman/Issues#206]
Hello Eric,

during SANS FOR508 course, it is mentioned multiple times that your tools https://ericzimmerman.github.io/#!index.md can run on Linux with .NET6. I wanted to install all your tools within SIFT VM, however I have not found sources to all your tools on github (so I cannot build them on Linux). Would it be possible to share Linux builds of your tools please?

**Comment by EricZimmerman** [comment]
They are all on ericzimmermantools and every repo is available under my acct here. Thats the nice part about net 6, the DLL IS the same on every operating system. 

You can use the PS1 on Linux as well to download all the stuff. 

Downloading the net 6 binaries and using 

dotnet LECMD.dll is all it takes. 

You can build all the tools if you want but there's no need.

**Comment by WW0nka** [comment]
Thanks it works.

What about to add them directly into SANS SIFT VM image, with aliases and symlink in /usr/local/bin? To be run as commands directly form any location.

**Comment by EricZimmerman** [comment]
Sure just alias the commands. I dont maintain soft so I couldn't do it but mark hallman at sans has a list of aliases already
