### ISSUE TITLE
TimelineExplorer unable to load any plugins

### ISSUE THREAD

**Issue by pearldarkk** [EricZimmerman/Issues#207]
Hi.

I can't have my TimelineExplorer to load any plugin. Here is the message.
![image](https://github.com/EricZimmerman/Issues/assets/58837237/21c0e397-7717-49e8-88dc-2130dd7a5cd3)

All the dll files are still there. I copied the TimelineExplorer folder from another computer with 7z but extract on this computer with winzip.
I have read some close issued and tried to unblock the dlls with this commandline but it didn't work either:
```
cacls <all dll> /P everyone:f
```

Since I can't install 7z on this computer, can you suggest any other way to fix? Or have i misunderstood the problem?
Thanks for helping.

**Comment by EricZimmerman** [comment]
Go into the plugins folder, right click on each DLL, choose properties and then remove the block check box

Click okay and repeat for every single other DLL

**Comment by pearldarkk** [comment]
I have unlock dlls with cmd and this is properties of all dlls:

![image](https://github.com/EricZimmerman/Issues/assets/58837237/52df8227-cedd-477e-bd6c-f4a1a1b68c33)
![image](https://github.com/EricZimmerman/Issues/assets/58837237/c5d17df0-e71f-425e-8659-718687a70222)

**Comment by pearldarkk** [comment]
Also, I did try to unblock these with powershell:
![image](https://github.com/EricZimmerman/Issues/assets/58837237/08e70d2e-4ceb-4c8f-987c-278f2ad56983)

Then I close TimelineExplorer and open again but still didn't work.

**Comment by AndrewRathbun** [comment]
If you're on Windows 11, this should be solved soon! 

```
7-Zip and RAR support
Windows 11 23H2 is also expected to natively incorporate support for RAR and 7-zip archival formats with the new integration for the “libarchive” open-source project.

The support will add seamless integration to open and extract many archival file formats (such as “.tar,” .tar.gz,” “.tar.bz2,” “.tar.zst,” “.tar.xz,” “.tgz,” .tbz2,” “.tzst,” .txz,” .rar,” and “.7z”) in the same fashion you do today with Zip files through File Explorer. It’s also possible that Microsoft will add support to manage RAR and 7-zip with commands using PowerShell and Command prompt.
```

Maybe you need to use .ZIP and not .7Z until this feature comes to Windows 11 in a few days.

**Comment by pearldarkk** [comment]
I used it on Windows Server 2016. 
I managed to install 7z and extract TimelineExplorer.zip with it, but still didn't work.

**Comment by EricZimmerman** [comment]
Use my power shell installer. Try a different machine. Maybe it's something In your environment doing it.

**Comment by EricZimmerman** [comment]
Look at the error message

It's complaining about not being able to find .net standard 2.0
So either reinstall .net 6 or find a different machine because that one is broken

**Comment by EricZimmerman** [comment]
You appear to be using timeline explorer 1.3 for some reason. In that case, you're going to need to install.net 4.8

I would just change over the timeline explorer 2.0 and then you'll just need.net 6

**Comment by pearldarkk** [comment]
Thanks for helping. I managed to reinstall .NET and it worked!
