### ISSUE TITLE
HTTP 404 Not Found

### ISSUE THREAD

**Issue by neomafo88** [EricZimmerman/Issues#210]
- https://f001.backblazeb2.com/file/EricZimmermanTools/All.zip
- https://f001.backblazeb2.com/file/EricZimmermanTools/net6/All_6.zip

```
{
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}
```

Source https://ericzimmerman.github.io/#!index.md
> Need everything at once? Here are ALL the tools as a single zip file: [.net 4](https://f001.backblazeb2.com/file/EricZimmermanTools/All.zip) | [.net 6](https://f001.backblazeb2.com/file/EricZimmermanTools/net6/All_6.zip)

**Comment by AndrewRathbun** [comment]
Confirmed those links don't work.

**Comment by EricZimmerman** [comment]
Yeah those are gone on purpose

I need to update the main page but for whatever reason somebody was downloading the files over and over and over again which started to cost me quite a bit of money

Use the power shell script. It'll download everything for you

**Comment by EricZimmerman** [comment]
someone, somewhere, was downloading the full zip files over and over and over to the tune of 10gb a day. no idea if intentional, but certainly unwarranted, and this is the reason this is now gone

**Comment by AndrewRathbun** [comment]
No good deed goes unpunished :)
