### ISSUE TITLE
Timeline Explorer fails to process MFTEcmd file due to changed field definitions

### ISSUE THREAD

**Issue by ydkhatri** [EricZimmerman/Issues#214]
As a consequence of fixing the bug here - https://github.com/EZToolsManuals/EZToolsManuals/issues/55, we have a dependency that fails. 

TLE relies on field definitions which I think are sourced from the plugin DLL that ships with it. 
After updating MFTEcmd, TimelineExplorer does not load the output file now as it still expects a signed value (**System.Int16**) for ParentSequenceNumber. 
```
2024-03-11 04:57:56 [Error]: Error processing "C:\...\20240311001409_MFTECmd_$MFT_Output.csv": "The conversion cannot be performed.    Text: '37767'    MemberName: ParentSequenceNumber    MemberType: System.Nullable`1[[System.Int16, System.Private.CoreLib, ...
```

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/TLEFilePlugins/blob/a69ee373cd602741c95179dcd6b6bfb3a3ec7c77/TLEFileEZTools/EZTools.cs#L303

This is the DLL in question for that MFTECmd output. Passing this along for the good of the order.

**Comment by EricZimmerman** [comment]
Updated that DLL. can you download TLE update and see how it looks?

**Comment by ydkhatri** [comment]
I ran the Get-ZimmermanTools script to get both the net4 and net6 updates, and it seems to only update the DLL for net6 version of TLE, which gets the new DLL and works perfectly now. 
No update for net4.

**Comment by EricZimmerman** [comment]
Nor will there be. Net 4 gui apps are dead and gone as of today and won't ever be updated again. It's been 2 years.
