### ISSUE TITLE
TLE: Session that doesn't keep filtering and dragged columns

### ISSUE THREAD

**Issue by Droid-HK47** [EricZimmerman/Issues#215]
Hello here,

I don't know if it's a bug or not, but when I load a previous session of TLE that I saved, nearly everything is reset, no more dragged columns or filters are applied (column filters).

Would be good to keep all of those because filtering false positive is cumbersome and I will want to quickly see the state of my investigation when I come back on the file later on.

Except keeping the files open, the session doesn't do much for me.

Let me know if it is intended, otherwise it would be a cool feature.

Cheers

**Comment by EricZimmerman** [comment]
Is it a supported file, or a generic csv? The messages tab would say.

**Comment by Droid-HK47** [comment]
It's Generic CSV/TSV plugin, it's a hayabusa output.

So I presume it isn't possible to store the layout state somewhere to reload it later on when it's a generic CSV file. Would have been awesome

**Comment by EricZimmerman** [comment]
That's why. Toe doesn't know what it is 

If you send me a sample with a header row and maybe 10 data rows I'll add support.

**Comment by Droid-HK47** [comment]
Thank you for the quick answer !

Infortunately, the output fields change according who you are launching Hayabusa. Thus I like to use TLE for a lot of different kind of CSV's as well. 

But, since Hayabusa is pretty used, maybe it's useful for you :
[sample.csv](https://github.com/EricZimmerman/Issues/files/15076161/sample.csv)

I thought the layout state was agnostic of the CSV content, just storing the applied state regarding using the column names whatever those names are "expected" or not. But I will live with that, thank you a lot !

**Comment by EricZimmerman** [comment]
It's gonna be an issue if there's 20ndofferent header formats. That's how tle knows what kind of file it is. Why would they change?

**Comment by Droid-HK47** [comment]
Here the command : https://github.com/Yamato-Security/hayabusa?tab=readme-ov-file#csv-timeline-command

It seems my output might be the unique one for CSV regarding the header (not necessarily for the content).

The tool advertised the benefit to be much more readable with TLE by the way ! :)

**Comment by EricZimmerman** [comment]
It would be ideal if the csv was consistent. Maybe suggest it to the dev?

**Comment by Droid-HK47** [comment]
I have tried to reach them out : https://github.com/Yamato-Security/hayabusa/issues/1333

So they are 4 profiles that are really commonly used : standard, minimal, verbose, super-verbose.

The user can change the name of the column if they want it, but it can be assumed they know that won't be compatible for certain things afterwards.
They assume the column pattern of those profiles aren't planned to change. 

So if you want to support the standard profile, or even more of them, it would be interesting. Otherwise I have given a shot ! :)

Thank you anyway !

**Comment by AndrewRathbun** [comment]
Assuming each profile is a preset of column names and data types that won't change, can you provide the column names for each of the 4 and 10 or so rows of sample data so we can flesh out a plugin?

**Comment by Droid-HK47** [comment]
Hello here,

There the headers :

1. minimal profile output
%Timestamp%, %Computer%, %Channel%, %EventID%, %Level%, %RecordID%, %RuleTitle%, %Details%

2. standard profile output
%Timestamp%, %Computer%, %Channel%, %EventID%, %Level%, %RecordID%, %RuleTitle%, %Details%, %ExtraFieldInfo%

3. verbose profile output
%Timestamp%, %Computer%, %Channel%, %EventID%, %Level%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %RuleTitle%, %Details%, %ExtraFieldInfo%, %RuleFile%, %EvtxFile%

4. super-verbose profile output
%Timestamp%, %Computer%, %Channel%
, %EventID%, %Level%, %RuleTitle%, %RuleAuthor%, %RuleModifiedDate%, %Status%, %RecordID%, %Details%, %ExtraFieldInfo%, %MitreTactics%, %MitreTags%, %OtherTags%, %Provider%, %RuleCreationDate%, %RuleFile%, %EvtxFile%

Here the data :
[hayabusa__minimal.csv](https://github.com/EricZimmerman/Issues/files/15093371/hayabusa__minimal.csv)
[hayabusa_super_verbose.csv](https://github.com/EricZimmerman/Issues/files/15093374/hayabusa_super_verbose.csv)
[hayabusa_verbose.csv](https://github.com/EricZimmerman/Issues/files/15093375/hayabusa_verbose.csv)
[hayabusa_standard.csv](https://github.com/EricZimmerman/Issues/files/15093376/hayabusa_standard.csv)

**Comment by EricZimmerman** [comment]
Perfect. A bit more work but now each can be supported. I'll see if I can do this today.

**Comment by Droid-HK47** [comment]
You are lighting fast, thank you !

**Comment by EricZimmerman** [comment]
this is done. please update TLE and give it a whirl.

for some stupid reason, they use a dumb format for some of the dates, and use a - when there isnt one, so those columns are treated as a string

why use a real timestamp format for Timestamp, but yyyy/MM/dd for RuleModifiedDate and RuleCreationDate?

makes no sense and makes parsing harder

**Comment by Droid-HK47** [comment]
Thank you a lot !
