### ISSUE TITLE
Voron/Klipper backup to Github needs update for my sqlite

### ISSUE THREAD

**Issue by MallocArray** [EricZimmerman/Issues#216]
The autocommit.sh script was updated for Moonraker moving the database to sqlite, but the markdown file still mentions downloading lmdb-utils.

Should remove the references to lmdb-utils and maybe make mention of the new database format?

**Comment by EricZimmerman** [comment]
I'll adjust the writeup.

**Comment by EricZimmerman** [comment]
Writeup fixed. Pr done against main voron docs.
