### ISSUE TITLE
[RegistryExplorer] First run and `System.IO.DirectoryNotFoundException: C:\Users`

### ISSUE THREAD

**Issue by XakerTwo** [EricZimmerman/Issues#219]
First of all - directory is really does not exist in any form! System is very customized

Main issue - using constants(i assume) for things that even system assumes are variables.

Consequences - nothing under `File`.`Live system`.`Users` - sub-menu does not show at all

Solution - use environment variable `%UserProfile%` and step one folder up or read `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\ProfilesDirectory` (preferred)

</br>

Additionaly:
`C:\Users` does not exists in any form and to clarify a bit more - `C:\Users` changed to `G:` and `%AppData%` in my system looks like `G:\Xaker_Two\AppData\Roaming` <sup>no `Users` folder at all</sup>

Don't assume that `Public`, `Default` and `ProgramData` will always be in the same location (and for `Default` hive you have no choose but read `ProfileList\Default` reg key)

**Comment by EricZimmerman** [comment]
i dont think this is something i will be fixing. its too rare of an edge case to worry about, at least for now

those options in the menus are more for convenience than anything else. you can always run RE as admin and manually browse to the hive locations to open them with these non-standard locations

**Comment by XakerTwo** [comment]
convenience is why i try your soft instead of mounting hive with regedit. yes this issue for me is not an issue at all cuz i not need "live" hives, but exception on start is well annoying, and for other persons who not so familiar where to search "live" hives this can be an issue

for this issue i will be glad to see fix or atleast answer - does it so hard to add one or both changes in `Main_Load`:

<details><summary>atleast wrap the obtaining of sub-dirs with try-catch to prevent this</summary>

![image](https://github.com/user-attachments/assets/65944771-f308-4f30-8626-ba7f9332dc1e)
</details>

• replace magic strings with variable and add reading of one or other registry key for proper registry loading, or atleast use environment variable

?

if so - ok, not an issue for me, atleast i have two options to solve it privately on my side. just give me answer one more time

and about convenience - there one more issue i will report separately (themes related)
