### ISSUE TITLE
ShellBags Explorer - Feature Request

### ISSUE THREAD

**Issue by chadtilbury** [EricZimmerman/Issues#22]
It would be helpful to pull some of the shellbag details into a format that can be more quickly understood by an analyst.  It feels like some of the most important information is buried in the details tab and would be more useful in a “summary” view.  As an example, the folder target timestamps are separated (likely due to being from different blocks) but would be more useful together along with clearer messaging about what folder they belong to. 

It would also be nice to have a better distinction between Parent and Current Item information.  It is sometimes difficult to determine if timestamps in the Details view relate to the current key (folder) or are parent information.  As an example, the Last Write Time in details is from the folder’s parent, not the folder currently selected.  

A sample "summary" mock-up is below:
 
Summary
Short name: Users
Absolute Path: Desktop\My Computer\C:\Users
Bag Path: Local Settings\Software\Microsoft\Windows\Shell\BagMRU\1\1\0       [1]           
Registry Last Write Time: 2013-08-01 19:22:31          [2]
 
Target Timestamps
Modified: 2013-08-10 03:03:24.000
Created On: 2012-07-26 05:38:00.000
Last Access: 2013-08-10 03:03:24.000
 
Value: Users
Shell Type: Directory
Node Slot: 216
Number of Child Bags: 1
[3] 

Parent Bag Path: BagMRU\1\1, Slot #: 0, MRU Position: 0   
Last Interacted (last write time from parent): 2013-10-20 22:21:09.148       [4]

[1] The reg path that holds the data for the “Users” folder.  This makes it clearer without having to add the Slot # to the Bag Path value currently shown in details.  The full path makes it easier cross-reference in the actual registry
 
[2] Last write time of BagMRU\1\1\0 (the current last write time shown by SBE is of the parent key, which is the grandparent of what is in the Values table and hence less useful.  This will have the added value of matching one of the last interacted times in the table, making it easier to see how one child gets the last write time of the parent

[3] First Interacted Time would be here if Child Bags = 0

[4] Last Interacted time only if MRU Position = 0 in the parent folder

**Comment by EricZimmerman** [comment]
for 1, why would you ever need to cross-reference anything, except maybe once, to verify SBE?

last write time reflects the key where the data comes from, so i am not seeing how this is an issue. would it be more clear if it said "Parent key last write time"?

![image](https://user-images.githubusercontent.com/4265254/45450082-1439ee00-b6a5-11e8-9858-5fc0f31e9485.png)


what I would like is some screenshots showing what SBE currently is doing, vs what you want it to do, so I can see how what you are envisioning can get pulled into the summary.

ideally you could provide a hive (or let me know and ill send you one) that you can load in SBE, pick a shellbag, then draft  how youd like to see that as a summary, along with where the information comes from. happy to do this this week, but i need more details so we get it right the first time.

**Comment by EricZimmerman** [comment]
this is what i am going with so far

![image](https://user-images.githubusercontent.com/4265254/45486444-1cd40800-b729-11e8-8a2b-533510a67b04.png)

**Comment by EricZimmerman** [comment]
to #2, the last write timestamp has nothing to do with what is shown in values window, but rather, it is the last selected shellbags registry keys last write timestamp. the panes at the bottom reflect the details on the last thing clicked, be it in the values window, the tree on the left, etc.

the selected item in the tree is shown in bold (as seen above)

Summary will look more or less like this:

![image](https://user-images.githubusercontent.com/4265254/45492448-56613f00-b73a-11e8-8faf-c7623c4edf6b.png)

**Comment by EricZimmerman** [comment]
Gonna close this for now and we can polish Summary if need be. this will be in v1.1 of SBE
