### ISSUE TITLE
[RegistryExplorer] Text color issue with dark themes

### ISSUE THREAD

**Issue by XakerTwo** [EricZimmerman/Issues#220]
<details><summary>demo</summary>

![image](https://github.com/user-attachments/assets/8a7dc922-f55b-45ca-9aa4-8a4c271f2d21)

</details>

probably this and similar gradients should be adapted to theme?

affected themes
- Office 2019 Black
- Office 2016 Black (on demo)
- DevExpress Dark
- VS 2013 Dark
- Bonus.DarkSide
- Bonus.Darkroom
- Bonus.Metropolis Dark
- Bonus.Sharp Plus

**Comment by EricZimmerman** [comment]
The themes are from devexpress. I can't change them. 

You can change the background colors via editing the conditional coloring rules tho. Right click on a column header and see the conditional formatting.

**Comment by XakerTwo** [comment]
Are you sure? Nothing can be changed in `SetupValueGrid()` ? Nothing like `Color.SeaShell` and `Color.Salmon` with `Color.MediumOrchid` ? those colors is assigned by your code and probably you can add red or yellow tint to theme's `BackColor` on the fly, there should be nothing hard. you can even cache those colors until theme changed

**Comment by EricZimmerman** [comment]
Ya. I'm sure. Use a different theme I suppose. 

I cannot accommodate every individual users preferences. There's dozens of themes. One should work.

**Comment by XakerTwo** [comment]
adding tint to theme's color is well dynamic solution

All dark themes affected - ALL, light and silver is not an option for me

ok, i understood

<sub>if the one should work then maybe only this one should exist?.. (not a guide to action)</sub>
