### ISSUE TITLE
TimelineExplorer keeps loading when opening log files

### ISSUE THREAD

**Issue by enen99912** [EricZimmerman/Issues#224]
Timeline Explorer v2.0.0.1, when trying to open a log file of about 770MB, it seems like keep loading and will not open the files. How to know whether it is a file size limit or my resources issue?
![image](https://github.com/user-attachments/assets/12ec0af1-82c2-45fc-924f-d00f914a7844)

**Comment by EricZimmerman** [comment]
You can open up the messages tab and see what it's doing and optionally enable debug before you open it 

Timeline explorer can handle 15 gig CSV so your file size isn't an issue

**Comment by AndrewRathbun** [comment]
It's probably bad data. Turn on Debug messages and try reloading the file.

![TimelineExplorer_Ob3tnzq9v0](https://github.com/user-attachments/assets/a040dc53-ad18-4c3a-bec2-5516d1bede0f)

**Comment by enen99912** [comment]
Thanks a lot! From the Messages, it shows something like below. 
2024-10-18 01:17:20 [Warning]: Bad data found in "10.x.x.x - - [17/Oct/2024:09:09:00 +0800] \"POST /example_path....."

Actually the file extension is .log file instead of csv file. Will this cause the issue?

**Comment by AndrewRathbun** [comment]
Are these IIS Logs? If so, you may want to try using IISGeoLocate on them instead. It'll chunk them out into CSVs nicely.

**Comment by EricZimmerman** [comment]
Iis logs would not work well as is.

**Comment by AndrewRathbun** [comment]
If they are in fact IIS logs, try a command similar to the one found here on them: https://github.com/EricZimmerman/KapeFiles/blob/7bcb702d78df14d6d8b7b224a1f2a6a2465ea493/Modules/EZTools/iisGeoLocate.mkape#L11

**Comment by enen99912** [comment]
It is actually a reverse proxy access log, with common log format. Will it be supported?

**Comment by EricZimmerman** [comment]
No idea

What does the format look like? 

You can certainly add support to the plugins for that format as well.

**Comment by AndrewRathbun** [comment]
@enen99912 can you provide 10 sample lines including headers here?

**Comment by enen99912** [comment]
The following are just the sample. 

Headers: 
IP Address, User Identifier, User Authentication, Timestamp, Request, Response Status, Bytes, Referrer, User Agent, Optional Header, Request Time, Upstream Response Time

Logs: 
192.168.1.10 - - [21/Oct/2024:12:34:56 +0000] "GET /api/v1/users HTTP/1.1" 200 1234 "https://example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"0.025 0.025
203.0.113.5 - - [21/Oct/2024:12:35:02 +0000] "POST /api/v1/login HTTP/2.0" 401 678 "https://example.com/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) Gecko/20100101 Firefox/117.0" "-"0.028 0.028
198.51.100.23 - - [21/Oct/2024:12:35:15 +0000] "GET /api/v1/products/123 HTTP/1.1" 404 512 "https://example.com/products" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15" "-"0.025 0.025
192.168.1.11 - - [21/Oct/2024:12:36:20 +0000] "GET /api/v1/orders HTTP/1.1" 200 2048 "https://example.com/orders" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"0.026 0.026
203.0.113.5 - - [21/Oct/2024:12:37:05 +0000] "POST /api/v1/cart HTTP/2.0" 201 256 "https://example.com/cart" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) Gecko/20100101 Firefox/117.0"  "-"0.027 0.027
192.168.1.12 - - [21/Oct/2024:12:37:18 +0000] "GET /api/v1/users/45 HTTP/1.1" 200 1024 "https://example.com/users/45" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"0.022 0.022
198.51.100.23 - - [21/Oct/2024:12:38:10 +0000] "GET /api/v1/products HTTP/1.1" 200 5120 "https://example.com/products" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15" "-"0.023 0.023
192.168.1.13 - - [21/Oct/2024:12:39:01 +0000] "PUT /api/v1/users/45 HTTP/1.1" 204 0 "https://example.com/users/45/edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"0.049 0.049
203.0.113.6 - - [21/Oct/2024:12:40:12 +0000] "GET /api/v1/orders/789 HTTP/2.0" 200 1536 "https://example.com/orders/789" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) Gecko/20100101 Firefox/117.0" "-"0.075 0.075
198.51.100.24 - - [21/Oct/2024:12:41:25 +0000] "DELETE /api/v1/cart/123 HTTP/1.1" 204 0 "https://example.com/cart" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15" "-"0.034 0.034

**Comment by AndrewRathbun** [comment]
Well, I can see there are no comma-separated values, so I can see where TLE is having an issue. There are comma-separated column headers, but then no data underneath that's comma-separated. So there's an unstructured structure 😆

**Comment by enen99912** [comment]
Actually the logs doesn't have headers included. It just simply contains all those log entries (which are not comma-separated). Thus, meaning that these kind of logs are not intended to be viewed in TLE which require formats as in CSV file?

**Comment by EricZimmerman** [comment]
Correct. Tlenia for CSV, TSV,  and excel files.

**Comment by AndrewRathbun** [comment]
TLE can also ingest flat text files to add Line and Tag columns, but that format is supported more out of convenience than to fully flesh out its functionality, given that there are a million text editors/viewers out there.

**Comment by enen99912** [comment]
Thanks both for patiently answering my questions ya. Greatly appreciated.
