### ISSUE TITLE
case sensitivity with transaction logs

### ISSUE THREAD

**Issue by grayfold3d** [EricZimmerman/Issues#29]
I've been running into issues running SBECmd and Amcacheparser when the transaction logs and hive files contain a different case type. For example, NTUSER.DAT and ntuser.dat will return the attached error in SBECmd.exe. I'm using the DBlake image from FOR500.  

I get a similar error running Amcacheparser but since that tool allows you to specify the file, I can change its case to match the transaction log names.
![sbecmd_error](https://user-images.githubusercontent.com/18709690/42982001-323aeba2-8bad-11e8-990b-93983c42d43e.jpg)

**Comment by EricZimmerman** [comment]
hi, this is an FTK issue i believe. it certainly looks like you mounted an image with ftk imager, etc and accessed the mount to try this. it doesnt work using the defaults. i would try:

1. copying the hive and log files out to a separate directory
2. using arsenal recon image mounter and dump ftk =)

rob lee had the same issue and worked around it with those methods if i recall.

it should not be a capitalization thing, but rather, an FTK doesnt work thing.

please give it a try and let me know.

**Comment by grayfold3d** [comment]
OK yeah you are correct.  They don't process if using FTK when the hive and transaction log are capitalized differently. The attached screenshot illustrates this.  
When using Arsenal or copying to a separate directory it works. 

![image](https://user-images.githubusercontent.com/18709690/43007527-9752bf20-8c06-11e8-8eb0-fb5951717bd0.png)

**Comment by EricZimmerman** [comment]
woot woot! closing the issue.

DIAF FTK!
