### ISSUE TITLE
PECmd Errors when processing Volume Shadow Copy 

### ISSUE THREAD

**Issue by grayfold3d** [EricZimmerman/Issues#37]
Receiving several errors when running PECmd against a VSC mounted with VSCMount or Prefetch folder extracted by Shadow Explorer. I've tried two images including the LoneWolf image so you can use that as reference if needed.
I've mounted the disk using Arsenal, used 'write temporary' and then ran the following command.
`PECmd.exe -d C:\cases\DesktopVSC\VSCMount_I\vss019\windows\prefetch  -q --csv c:\cases\TestVSC\`

Resulting in errors like these:

![2018-09-30 22_37_40-pecmd-error](https://user-images.githubusercontent.com/18709690/46267214-8d3ca080-c501-11e8-8bd5-1c57a54b6103.png)

**Comment by EricZimmerman** [comment]
what do the headers look like for those files? What version of PECmd are you using?

i assume you are running windows 10 because some of those looked to have parsed ok

Im getting the lone wolf image now and will check here, but let me know on the above ittems

**Comment by EricZimmerman** [comment]
The files with Invalid signature ones, that i checked, were all 00s, so those i cant do anything about.

working on the other ones now to see if i can tell whats up

**Comment by grayfold3d** [comment]
I'm running PECmd 1.1.0.0 and Win 10. 
Just looking at the headers now.  I noticed that other Prefetch tools(like WinPrefetchView) also fail to fully parse the ones with the Win10 decompression error.  Could these still be parsed based off the file times? So at least we'd have the first/last time run?

**Comment by EricZimmerman** [comment]
im working thru it now, there is a decompression error (ie it doesnt return 0 as a result of the call to the WinAPI to decompress the file), so im only getting partial data. i am not a fan of partial parsing because people tend to ignore the errors, but i will see what i can do to get around this issue. maybe if there is an error ill dump the details we have to the screen and call it a day for that one. playing with this now

**Comment by EricZimmerman** [comment]
ok, i think i have this working to a  point where i am happy with it. Now it will parse what it can and report it

![image](https://user-images.githubusercontent.com/4265254/46297862-b85bda00-c56b-11e8-80db-e275bf5175c7.png)


will push update here soon.

**Comment by EricZimmerman** [comment]
v1.2.0.0 is up

**Comment by grayfold3d** [comment]
Great. Thanks Eric!
