### ISSUE TITLE
SBECmd stuck in loop executed against drive mounted in SIFT Workstation

### ISSUE THREAD

**Issue by grayfold3d** [EricZimmerman/Issues#38]
Running SBECmd.exe version 1.1.0.0 on Windows 10.
I realize this may be a fringe use case but I'm running SBECmd against an imaged mounted in SIFT and it looks like it's just stuck in a loop.  On a normal drive mounted in FTK or AIM, I can 
run something like  `SBECmd.exe" -d "i:\users" --csv "G:\Cases\Desktop-SBECmd"` and it will run for each user.  
When I run the following - 
`SBECmd.exe" -d "\\192.168.1.166\mnt\windows_mount1\users" --csv "C:\Cases\Desktop-SIFTMount"` - it does create the normal output files for the first user but then it keeps appending "Application Data" to the path name and scanning the same UserClass.DAT file over and over. The screenshot below of the file names it is creating should show you what I mean.  Eventually the file name length exceeds 255 characters and they stop being created.

![image](https://user-images.githubusercontent.com/18709690/46372184-65ac1c00-c658-11e8-80fe-1e2f236bf7a6.png)

Here is the log. 
[!SBECmd_Messages.txt](https://github.com/EricZimmerman/Issues/files/2439399/SBECmd_Messages.txt)

**Comment by EricZimmerman** [comment]
this is a reparse point issue. i know the fix. will roll it into SBECmd here tomorrow probably.

**Comment by EricZimmerman** [comment]
ok now that i look at this more, its not a reparse issue, because your first case is working correctly and i already have code in SBECmd to handle this situation. did you mount one of the SANS images to make this happen, or are you running this against your own case?

ill have to mount an image and see if i can replicate it, but the first choice of using AIM (always better than FTK) to mount the image is the ideal one for a lot of reasons.

**Comment by EricZimmerman** [comment]
please email me at saericzimmerman AT gmail DOT com so can send you a build to test to see if i have this resolved for you.

**Comment by grayfold3d** [comment]
email sent

**Comment by EricZimmerman** [comment]
This is a SIFT issue and i cant fix it. For whatever reason, when you access this via SAMBA (maybe its a samba issue?) it keeps showing the Application data directory over and over and over which is clearly wrong. That is a repart point afaik, so it shouldnt be doing that.

![image](https://user-images.githubusercontent.com/4265254/46417162-0c46fa00-c6f7-11e8-99b8-08b4d010acdc.png)

AIM seems to work just fine for all the images i have tried, including MaxPowers, etc.
