### ISSUE TITLE
CSV option as export

### ISSUE THREAD

**Issue by SIFT-OWNER** [EricZimmerman/Issues#4]
CSV please as default.  Please.  While TSV works excel needs to import it. Or make an option to change delimiter to csv or tsv.

**Comment by EricZimmerman** [comment]
This is done and updated apps plus TLE with csv support was sent to Rob for testing/verification. will release the updates for all tools once i hear from him

**Comment by EricZimmerman** [comment]
question, right now i have the --cs (use csv separator) option as false by default (ie tsv is still default). im leaning toward making csv the default. thoughts?

**Comment by EricZimmerman** [comment]
This is done pending testing. will release updates for all tools once testing is validated
