### ISSUE TITLE
AmCacheParser not parsing dirty hives

### ISSUE THREAD

**Issue by gc-nibrahim** [EricZimmerman/Issues#41]
I have two separate instances of AmCacheParser not being able to parse dirty Amcache.hve files. Other tools are able to parse the hives. Screentshot below of errors.

![image](https://user-images.githubusercontent.com/16657143/46900297-84cf5880-ce65-11e8-94aa-6bab7aa8f1c4.png)

**Comment by EricZimmerman** [comment]
Do the hives parae without the transaction logs present? (Hold shift while
running to byoass dirty warning).

How did you extract the log files? If you look at the contents of the logs
is there data?

Do the tools that parse it honor transaction logs?

Finally can I get the files to test here?

**Comment by gc-nibrahim** [comment]
No it does not parse without the transaction logs. Tried using the hold shift feature. Doesn't appear to be available for this parser. I used it in your other tools though.

It would be amazing if the hold shift option was a switch for batch processing purposes.

FTK Imager was used to extract. Yes, there is data in the logs.

Unsure if the other tools are honoring the transaction logs. 

Files are attached.
[AmCache.zip](https://github.com/EricZimmerman/Issues/files/2475688/AmCache.zip)

**Comment by EricZimmerman** [comment]
I'll take a look. Can you extract with aim and see if results are same?

**Comment by EricZimmerman** [comment]
it looks like one of the logs has bad/damaged/encrypted/???? data in it. this is where thing are falling down.

The hive processes fine without the logs, but once they are applied it explodes.

im gonna see what yarp does when replaying the logs. im assuming the data is bad at this point tho.

with the new command line arguments to not reply the logs you will be ok, just nothing from the logs. with amcache, this is bad, but at least its something

will add more when i have a yarp hive to compare it to as a second check

**Comment by EricZimmerman** [comment]
this is fixed. had to check and verify the hash in the transaction log. AmcacheParser has been updated with the new Registry code (1.2.0.0) AND a --nl switch so you can disable log processing as required.

update is getting pushed now

**Comment by EricZimmerman** [comment]
also, do you know if you made the image where the hive and logs came from while the system was running, or was it a dead box that you imaged?
