### ISSUE TITLE
Lnk: Encoding bug in NetworkShareInfo

### ISSUE THREAD

**Issue by ldy985** [EricZimmerman/Issues#42]
The LNK parser currently crashes when encountering Unicode network names. Here is a test file: 
[说明.txt - Shortcut.lnk.zip](https://github.com/EricZimmerman/Issues/files/2482896/txt.-.Shortcut.lnk.zip)

**Comment by EricZimmerman** [comment]
strange. its looking for unicode info now. are there parsers you have found that work with this file? 

im working on things now to see what i can do, but its strange in that there looks like there is a mix of ascii and unicode in there.

![image](https://user-images.githubusercontent.com/4265254/47045499-f3abfa80-d160-11e8-806e-6d84ed3127b8.png)

**Comment by EricZimmerman** [comment]
i have this working

Network share information
Share name: \\ޓ\C

will update the project and LECmd soon as well

thank you much for the sample file!

**Comment by EricZimmerman** [comment]
lnk project updated, as is LECmd as of v1.1.0.2.

please test and let me know and i can reopen if needed.

**Comment by ldy985** [comment]
Works fine. Thank you for the quick response!
