### ISSUE TITLE
Add a lznt1 decompression plugin

### ISSUE THREAD

**Issue by dlcowen** [EricZimmerman/Issues#45]
Add a plugin for lznt1 decompression so we can decompress key values

**Comment by EricZimmerman** [comment]
one example is Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\CIT\System

on win7 it has strings of full path exes

**Comment by EricZimmerman** [comment]
https://github.com/DiscUtils/DiscUtils/blob/17988ab7ecd6592b51db30c1f50d8fe89b508297/Tests/LibraryTests/Ntfs/LZNT1Test.cs

https://github.com/DiscUtils/DiscUtils/blob/17988ab7ecd6592b51db30c1f50d8fe89b508297/Library/DiscUtils.Ntfs/LZNT1.cs

**Comment by EricZimmerman** [comment]
this this donezo! sent you plugin
