### ISSUE TITLE
RECmd feature request

### ISSUE THREAD

**Issue by grayfold3d** [EricZimmerman/Issues#46]
Add wildcard support to KeyPath in batch config file. A use case would be for things like ControlSet00*\Services (ControlSet001\Services) or SOFTWARE\Microsoft\Office\*\*\User MRU\*\File MRU (\Users\jcloudy\NTUSER.DAT: Software\Microsoft\Office\16.0\Excel\User MRU\LiveId_2709CD201D69E509465D3C60D830CE2490A74738D87E3C8A95FEFEA94316F09F\File MRU)

**Comment by EricZimmerman** [comment]
i need to have exact key paths you expect to find. the office one is not clear. i do not see those key paths in the lone wolf SOFTWARE hive.

Please provide, for lone wolf, the wildcard path you want to use and what you expect the key path to expand to.

t

**Comment by grayfold3d** [comment]
I updated the original issue with the path from the LoneWolf image. For some reason Github is replacing the backslashes in my path that has the wildcards? 

Here is a screenshot showing how I would configure that block in my batch config.  Using the wildcard at the end and setting it to recurse would get the File and Place MRU and their contents for all users on the system.
![image](https://user-images.githubusercontent.com/18709690/51038691-e5178880-1581-11e9-9a50-d38f305135da.png)

Here is a screenshot from RE of the keys I'm referring to. 
[
![2019-01-11 09_03_39-registry explorer v1 1 0 6](https://user-images.githubusercontent.com/18709690/51038318-dc728280-1580-11e9-9f52-2f2de17c19f0.png)
](url)

**Comment by EricZimmerman** [comment]
This should be done and in your hands. Please review and close this when done testing, else provide feedback on any issues. thanks!

**Comment by EricZimmerman** [comment]
round 2 sent to you

**Comment by grayfold3d** [comment]
Working as requested. Thanks again!
