### ISSUE TITLE
Lnk: ShellBag0x32 tries to parse regular link to file as zip content

### ISSUE THREAD

**Issue by kkriisgaard** [EricZimmerman/Issues#47]
I've encountered a bug in ShellBag0x32. It appears that if the byte at offset 0x28 is 0x2f, the shellbag is parsed as ZipContent.

I've found a case where the data on offset 0x28 is 0x2f, but said data is part of the beef. This leads to the file name in the absolute path being "unable to determine value". If I comment out the part where an attempt is made to parse it as a zip file, it works perfectly.

[I've prepared a test file for you.](https://github.com/EricZimmerman/Issues/files/2755263/EZ-Testfile.zip)

**Comment by EricZimmerman** [comment]
Fixed


Absolute path: My Computer\D:\Docs\Documents\Pro Cycling Manager 2014\Mod\Database\KKR2017_2.cdb

pushing updates to LECmd, JLECmd, and Jumplist explorer now

Thank you for the report!

**Comment by kkriisgaard** [comment]
Thank you for fixing it so quickly. I think you have a misplaced `return;` [here](https://github.com/EricZimmerman/Lnk/blob/master/Lnk/ShellItems/ShellBag0x31.cs#L45)

**Comment by EricZimmerman** [comment]
doh! fixing now and will push updates. no version bump.

**Comment by EricZimmerman** [comment]
updates pushed
