### ISSUE TITLE
Create a parser for wpndatabase.db.

### ISSUE THREAD

**Issue by EricZimmerman** [EricZimmerman/Issues#49]
http://www.swiftforensics.com/2016/06/prasing-windows-10-notification-database.html

**Comment by EricZimmerman** [comment]
@rathbuna add this to your TODO?

**Comment by EricZimmerman** [comment]
for sqlecmd i mean

**Comment by AndrewRathbun** [comment]
Added to the to-do list. Thanks for the heads up 👍

**Comment by AndrewRathbun** [comment]
https://www.github.com/EricZimmerman/SQLECmd/tree/master/SQLMap%2FMaps%2FWindows_Notifications_DB.smap
