### ISSUE TITLE
SBECmd: Fixing CSV column names

### ISSUE THREAD

**Issue by evild3ad** [EricZimmerman/Issues#50]
I'm using SBECMD in Windows PowerShell. 

The generating of the CSV output works, but when I try to import the CSV files (Import-Csv) to convert them on-the-fly to Excel (https://github.com/dfinke/ImportExcel) I get an error message, because two columns have the same name: IsEmpty

It seems that only unique csv column names are allowed. May you fix this
in the next version? e.g. IsEmpty#1 and IsEmpty#2

Thank you!

**Comment by evild3ad** [comment]
Fixed the issue in my Windows PowerShell script.

Multiple columns have the same name: IsEmpty, Width, Height, Flags

I removed the CSV header first and added my own header before importing with Import-Csv.

**Comment by EricZimmerman** [comment]
this seems like a parser issue vs columns with same name. glad you found a workaround
