### ISSUE TITLE
Jumplist Explorer v0.8.1.0 fails to parse this file

### ISSUE THREAD

**Issue by ydkhatri** [EricZimmerman/Issues#53]
Fails to parse the Microsoft.Photos (windows 10 builtin) app's jumplist file. Error is:  

`Error loading 'C:\testing\Recent\AutomaticDestinations\a52b0784bd667468.automaticDestinations-ms': Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
`
Jumplist Explorer version is  v0.8.1.0, on windows 10 (1709). The failing sample is attached.

[a52b0784bd667468.zip](https://github.com/EricZimmerman/Issues/files/2891229/a52b0784bd667468.zip)

**Comment by EricZimmerman** [comment]
This is done. pushing update out now

**Comment by EricZimmerman** [comment]
change is live
