### ISSUE TITLE
Registry Explorer REG_MULTI_SZ display

### ISSUE THREAD

**Issue by ydkhatri** [EricZimmerman/Issues#54]
It would help if the REG_MULTI_SZ strings would be displayed one on each line, as regedit does. See attached screenshots below.

**REGEDIT**
![regedit_multi-sz](https://user-images.githubusercontent.com/13247440/53270134-dbbd2800-36b8-11e9-9977-972faf2abd59.PNG)

**REGISTRY EXPLORER**
![registryexplorer_multi_sz](https://user-images.githubusercontent.com/13247440/53270135-dc55be80-36b8-11e9-9edb-f8723fd6b3cc.PNG)

**Comment by EricZimmerman** [comment]
sure, i can do this. thanks for the report!!

**Comment by EricZimmerman** [comment]
can you tell me the hive you used and some key/values where you are seeing this? easier than me hunting around

**Comment by EricZimmerman** [comment]
nevermind. found some.

here you go

![image](https://user-images.githubusercontent.com/4265254/53289324-a5d47e00-3762-11e9-927b-71cbce8463d0.png)


This is done and will be in next update. will probably just push the same build up here at some point today, so if you use the ps1 script it will see it and download the update.

**Comment by EricZimmerman** [comment]
change is live
