### ISSUE TITLE
RegistryExplorer Feature Request

### ISSUE THREAD

**Issue by Fetchered** [EricZimmerman/Issues#61]
Would like to ask for a couple of features be added:
- option to load all hives dirty without individual prompt (currently can select shift to apply transactions to all, or individually select the hive to replay transactions against, but not to load all hives as dirty)
- option to unload project; or
- option to unload all hives.

Cheers

**Comment by Fetchered** [comment]
Additional Feature Request:
- ability to sort by HIVE separately from 'key name'.
Currently when sorting by Key Name, it will sort the Hives alphabetically based on full-path, however it will also sort based on the keys in each hive.

**Comment by EricZimmerman** [comment]
what version are you using? RE has been able to unload all hives for a while:

![image](https://user-images.githubusercontent.com/4265254/54088962-d9ee9800-4339-11e9-9b60-8d84bccdfeaa.png)

ill have to see what i can do about the rest. the sorting one may not be possible. i suppose i could add a column to the tree view with hive path so you can sort by that first, then by keys. why sort the keys at all tho? filter or search or use bookmarks makes things way easier to manage, especially with available bookmarks

**Comment by Fetchered** [comment]
I'm currently using 1.4.0.0. 

What I meant to ask was primarily for the unload project, or close project which would unload all currently loaded hives in the project. What's happened recently is that I've unloaded all hives, loaded a couple more, then close RE and get prompted to save the project before exit. Of course, I choose to save, but then forget that I made changes to the project (since it was still open).
I could have been more clear on what I meant by that.

Sorting by keys would allow me to have all the NTUSER.DAT's from a system lumped together, or all the SYSTEM hives from various PC's together, regardless of their stored path. It helps when importing multiple hives and wanting to compare values/keys/lastwritetimes for certain things.

I also noticed when sorting by 'key', if I have three or more of the same hive open, it will also change the layout of which particular hive is at the top based on the path, then when I 'unsort/resort', I just have to remember that the hive that was at the top is not necessarily in the same position when I continue browsing through the keys. 

The bookmarks are great, however when I want a specific bookmark from multiple of the same hive (SYSTEM for example), and there are multiple hive types (software/sam/system/NTUSER), the bookmark sorting does the same thing, groups the hives by full-path and not hive type.

Not a deal breaker if you aren't able to get to it. This is still the best registry tool I've used, and I definitely appreciate all of the work you've put into it.

Thanks!

**Comment by Fetchered** [comment]
Just an FYI, I just noticed that there was a spelling mistake on the Context Menu. Option to Collapse subkeys reads as "Collape subkeys"

If you want another issue created, I can do that, but I didn't think you might want me to create another one just for a typo.

![Collapse](https://user-images.githubusercontent.com/10457978/54093258-62862c00-436c-11e9-96e6-594b2594d22b.PNG)

**Comment by EricZimmerman** [comment]
* 'collape' fixed
* added project unload

available in 1.4.3, out now
