### ISSUE TITLE
TLE: issue opening SBECmd csv output file

### ISSUE THREAD

**Issue by forensenellanebbia** [EricZimmerman/Issues#62]
When I drag the CSV output file created with SBECmd (1.3.1.0) into Timeline Explorer (0.8.13.0), nothing happens and no rows are displayed.

![TLE_SBECmd](https://user-images.githubusercontent.com/8271353/54465603-40c9e200-477c-11e9-8d8f-bfa4d4cbffd6.png)

Here's a snippet of the file I'm trying to load.

[c__temp_vm_reg_UsrClass.zip](https://github.com/EricZimmerman/Issues/files/2973154/c__temp_vm_reg_UsrClass.zip)

**Comment by EricZimmerman** [comment]
something is crazy. lemme look into it

**Comment by EricZimmerman** [comment]
This is fixed in v 1.3.2.0 which should be up now
