### ISSUE TITLE
TLE: field separator used in CSVs and OS regional settings

### ISSUE THREAD

**Issue by forensenellanebbia** [EricZimmerman/Issues#63]
When I open a .csv file containing a different field separator (e.g., a comma) from the one set in the regional settings (semicolon) of my operating system (Win10 1809), TLE (0.8.13.0) shows data in one single column. This behavior occurs for files for which TLE doesn't have a built-in support.

I looked at the "Quick help" and on your blog, but didn't find if there's a way to tell TLE which separator to use when needed.

**Comment by EricZimmerman** [comment]
Easy fix. Do not do that.

Use a comma or possibly a tab as that's all that is supported.

**Comment by forensenellanebbia** [comment]
Tried with a tab, but doesn't work.

![TLE_TAB](https://user-images.githubusercontent.com/8271353/54476849-0efb5e80-4802-11e9-84b1-7fa964652095.png)

**Comment by EricZimmerman** [comment]
A comma it is then.

There's always ezviewer if you want to try that

**Comment by forensenellanebbia** [comment]
I had the answer I was looking for, but I'm observing that TLE separates the fields for not directly supported CSVs if the field separator in CSVs matches the one set in the registry (HKEY_CURRENT_USER\Control Panel\International\sList). That means both have to be commas or semicolons. If I open a CSV with a comma, but my OS is set to a semicolon (my situation), TLE shows data in one column. This distinction doesn't happen for instance if I open a SBECmd csv output file containing commas of semicolons. I'll continue to use workarounds since I like TLE's filters. Thanks!

**Comment by EricZimmerman** [comment]
ok so for non-separated, it works as expected, but for ones that TLE directly supports (shows tag and line #) it must be a comma? is that what you are seeing?

the problem is knowing what to expect beforehand, so i know what the file type is to handle.

while i certainly can make TLE use the regional separator, i would then have to find a way to support it for all supported files. as you can imagine, this is a lot of stuff.

if you take a supported file, and change one of the header columns (just add an a to the end of one) and then load it in TLE, does it work as expected, or no?

right now, in that case, the separators should be CultureInfo.TextInfo.ListSeparator which seems like it would be region appropriate.

ah the joys of internationalization

**Comment by forensenellanebbia** [comment]
I ran some more tests. This is what I'm using:
- My analysis system: Win 10 Pro (10.0.17763) with Italian default regional settings (sList is set to ";")
- Test OS: Win 10 Home (10.0.10240) with US default regional settings (sList is set to ",")
- TLE: 0.8.13.0 

My system:
![myOS](https://user-images.githubusercontent.com/8271353/54478678-3f002d00-4815-11e9-81f0-12354a04ecb3.png)

This is what I'm experiencing on my analysis system. For files with TLE built-in support:

| CSV files (built-in support - e.g. CSV generated by SBECmd 1.3.2.0)      |  TLE, used on my system with sList=; |
| --------------------------------- | ---------------------------------- |
| if CSV contains ; as a delimiter (CSV created on my system) | TLE separates the fields           |
| if CSV contains , as a delimiter (CSV created on test OS) | TLE separates the fields           |

The problem seems to be for non-directly supported CSV files only. TLE expects to find in CSVs the same separator that retrieves from the OS (sList).

| Other CSV files (e.g. I used FTK Imager's file hash list which always contains comma separated values)                  | TLE, used on my system with sList=; |
| --------------------------------- | --------------------------------- |
| CSV created on my system and contains , as a delimiter | TLE shows data in one column          |
| CSV created on test OS and contains , as a delimiter  | TLE shows data in one column       |
| CSV created on my system and contains , as a delimiter. I then manually changed the commas with semicolons before opening the file with TLE | TLE separates the fields |

I then tried what you asked me: I took a supported file and modified one of its header columns. I used the ouput of SBEcmd.

**Case 1)** csv output created on my system and opened on my system. Columns are still correctly separated after modifying one header.

![ModifiedHeader_C_MySystem_O_MySystem](https://user-images.githubusercontent.com/8271353/54479784-fe0e1580-4820-11e9-884b-49e8e8709fab.png)

**Case 2)** csv output created on test system and then opened on my system. After modifying one header, columns no longer get separated.

![ModifiedHeader_C_TestOS_O_MySystem](https://user-images.githubusercontent.com/8271353/54479789-05352380-4821-11e9-990c-71d241d7d025.png)

When reading a CSV format that is not directly supported, could TLE ignore the regional settings and determine the right separator field to use by reading the first row of a file and checking the presence of , or ;?

**Comment by EricZimmerman** [comment]
yea but then what?
what if someone uses a | for a separator? or \ or any other symbol? thats the problem. too many variables.

ill play around with it to see what i can come up with

**Comment by fdncred** [comment]
I'd love to use a pipe | for the delimiter in TLE.

**Comment by EricZimmerman** [comment]
i cant possibly account for EVERY separator people may want to use.

**Comment by fdncred** [comment]
@EricZimmerman Maybe not an infinite number but you could put a separator textbox on the configuration to allow users to choose their own separator. Or put that option in some json/ini/registry settings.

**Comment by EricZimmerman** [comment]
, and tab are supported as is. i may look at this later, but its not a priority
