### ISSUE TITLE
MFTECmd: Be able to supply entry only to --de 

### ISSUE THREAD

**Issue by devgc** [EricZimmerman/Issues#64]
It would be helpful to be able to dump an entry with just the entry number.

Many times when tools error out on MFT specific issues they only provide an MFT entry number. If wanting to dump an entry from an MFT you currently have to specify a sequence number. This can require going "fishing" for additional info.

In my use case, I get an error from using TSK:
![image](https://user-images.githubusercontent.com/8633196/54543052-8ea03f00-4962-11e9-92ff-e067905598cd.png)

It does not supply me with the sequence number, thus I must search for its sequence number before being able to dump the entry.

**Comment by EricZimmerman** [comment]
as you know, FILE records are identified using Entry and Sequence #, so this is how i do it.

what if there were 2 file records with the same entry #? 

you can get the exact pair by using MFTECmd to dump the MFT in question.

however, with that said, let me see what i can do. maybe if there is more than one i can dump a list else just use the single one.

**Comment by devgc** [comment]
An entry number is just the offset number to the entry. The entry + sequence is the unique piece that can represent the file. Given 1 MFT, you could not have two records with the same entry number.

**Comment by devgc** [comment]
entry_number * MFT_ENTRY_SIZE gives you the MFT entry location

**Comment by EricZimmerman** [comment]
so there is NO way that you could ever have 2 structures in a single MFT for any reason with the same entry number? not on reuse or anything else? i treat each FILE record's key in a dictionary as entry-seq.

i am working thru this now to find a way to make this work given just an entry #

**Comment by EricZimmerman** [comment]
i cannot use the entry * size thing either because i do not just find and dump records. have to take extension records into account, so the MFT is processed then its dumped.

im on a solution tho! standby

**Comment by EricZimmerman** [comment]
ok this should be done. will send you a link to test

**Comment by devgc** [comment]
Works well for me!

**Comment by EricZimmerman** [comment]
ok close when you see fit! =)
