### ISSUE TITLE
RegistryExplorer plugin: Taskband

### ISSUE THREAD

**Issue by forensenellanebbia** [EricZimmerman/Issues#65]
When I navigate to the **Taskband** key and click on **Favorites**, I get this error:

_Errors: Error processing Favorites value '': Version mismatch! 90-ED-04-2D != 31-53-50-53, Error processing Favorites value '': Version mismatch! 90-ED-04-2D != 31-53-50-53, Error processing Favorites value '': Version mismatch! 90-ED-04-2D != 31-53-50-53, Error processing Favorites value '': Version mismatch! 90-ED-04-2D != 31-53-50-53, Error processing Favorites value '': Version mismatch! 90-ED-04-2D != 31-53-50-53_

![RE1420_Taskband](https://user-images.githubusercontent.com/8271353/55433843-8832d980-5596-11e9-9901-ea816d6f6b11.png)

Here's the NTUSER.DAT hive:
[ntuser.zip](https://github.com/EricZimmerman/Issues/files/3035829/ntuser.zip)

Apart from that, the Taskband tab gets populated. Thanks for the new plugin!

**Comment by EricZimmerman** [comment]
ah thanks, i will take a look tomorrow probably.

**Comment by EricZimmerman** [comment]
please redownload RE and try again. should be fixed now. if so please let me know and close this

**Comment by forensenellanebbia** [comment]
It's now fully working. Thanks
