### ISSUE TITLE
Specific User

### ISSUE THREAD

**Issue by cryptohasher76** [EricZimmerman/Issues#66]
The option to specify a user you are investigating with some of the triage.. 
  i.e.:   I want user XYZ's webbrowser triaged..   so it would grab only /User/XYZ/AppData/xxx..... and not everyone that connected to that system.   
   This would be helpful for when a specific user shares a workstation.

**Comment by EricZimmerman** [comment]
you can already easily do this:

1. make copies of the web browser targets and name them appropriately
2. replace the left most * with your target profile name (XYZ in your example above)
3. Run the new targets.

that or collect everything and delete what you do not need.
