### ISSUE TITLE
Registry Explorer/RECmd - Terminal Server Client plugin Date Parsing

### ISSUE THREAD

**Issue by grayfold3d** [EricZimmerman/Issues#67]
The Terminal Server Client Plugin provides a date which is the last write time of "NTUSER.dat: Software\Microsoft\Terminal Server Client\Servers" key. This date is listed beside each entry in the list of Servers/Hosts that the device has connected to by the plugin.  

Can you update this plugin to instead use the last write time for the subkeys containing the Hosts that the client has connected to? 

This is what is currently displayed. Note the timestamp is the same for all hosts
![image](https://user-images.githubusercontent.com/18709690/55895340-f9bbea80-5b89-11e9-98c3-f473bdcecc8e.png)

I'd like the timestamp displayed by the plugin to use the timestamps for each host.

![image](https://user-images.githubusercontent.com/18709690/55895180-9f228e80-5b89-11e9-9f53-1c5c6863be23.png)

**Comment by randomaccess3** [comment]
bump for this

**Comment by EricZimmerman** [comment]
doh, this was a bug. i had everything in place and the intention was to get the subkey, but i left the parent referenced.

fixed. will push updated RECmd out soon
