### ISSUE TITLE
Feature Request - MFTECmd - Add '--split' option to split large files

### ISSUE THREAD

**Issue by grayfold3d** [EricZimmerman/Issues#68]
Extremely large MFT files sometimes contain more entries than Microsoft Excel can open (Excel 2016 max is 1,048,576 rows). I know TLE can normally handle these but it would be nice to have an option to split the parsed MFT output into multiple csv files.

**Comment by EricZimmerman** [comment]
There are plenty of ways to do this already. My advice would be to not use Excel.

**Comment by grayfold3d** [comment]
Yeah I've used a couple of the splitting tools and have a PowerShell script that will do this as well but these add an extra step.  

Just a thought anyhow...feel free to pull out the "request denied" stamp :)

**Comment by EricZimmerman** [comment]
not worried about excel. =) open a ticket with MS or use TLE
