### ISSUE TITLE
Newline character parsing in Timeline explorer

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/Issues#70]
Timeline Explorer appears to be parsing `\n` as a newline even when it occurs normally in an event

![image](https://user-images.githubusercontent.com/4219694/56313574-e62bf900-6120-11e9-9daf-087409e46ea6.png)

**Comment by EricZimmerman** [comment]
fixed in 0.9.2.0

![image](https://user-images.githubusercontent.com/4265254/58749322-b1ff6400-8452-11e9-80ff-b5b7bd5fe97b.png)
