### ISSUE TITLE
TLE: Export CSV file to UTF-8

### ISSUE THREAD

**Issue by swepeba** [EricZimmerman/Issues#71]
When TLE exports marked rows to a new CSV file, the result is saved using Windows-1251. This means that I have to convert the CSV file to UTF-8 before opening it into TLE. Otherwise foreign letters like "åäöü" are exchanged. 

Would you please consider to **force** the use of UTF-8 when exporting to CSV from TE?

**Comment by EricZimmerman** [comment]
This should be fixed in v0.9.0.0 from this morning. download it again and give it a try. reopen if its not fixed. thanks!
