### ISSUE TITLE
SBECmd.exe command is not working

### ISSUE THREAD

**Issue by Hasi23** [EricZimmerman/Issues#73]
![CMD SS](https://user-images.githubusercontent.com/34801482/56861205-31af9400-69b8-11e9-98ab-ab0157750093.JPG)

As i have tried to run the command which is written in the SS but its not working and displays the message in CMD. What its mean and what should i write instead of that ?

Thanks

**Comment by EricZimmerman** [comment]
I'll fix it today but use the absolute oath for now vs a relative one

**Comment by EricZimmerman** [comment]
fixed. use the PS script to update or redownload from my site. no version # change

**Comment by Hasi23** [comment]
Thanks
