### ISSUE TITLE
TLE: Timeformat issue l2tcsv output

### ISSUE THREAD

**Issue by af104851b8** [EricZimmerman/Issues#75]
I've been getting the following error fairly frequently: 

Error: The DateTime represented by the string is not supported in calendar System.Globalization.GregorianCalendar

The format of the date is MM/DD/YYYY while the default is yyyy-MM-dd in Timeline Explorer. 
Other then that, there does not seem to be anything malformed in the date or time columns. 

The csv has been created with:
log2timeline -f filterfile output.plaso e01
psort -o l2tcsv -w output.csv output.plaso

Is there a debug mode to see what row it is having issues with?

**Comment by EricZimmerman** [comment]
What version of tle? Can you send me the first 25 or so rows?

It's probably a regional settings thing

**Comment by af104851b8** [comment]
I've found the issue. 
Some lines contain 00 in the day field for some reason: 
example : 01/00/1980,21:00:00,UTC

Replacing these lines resolved the problem.

**Comment by EricZimmerman** [comment]
sounds like a l2t issue then? this is good to know in case others have the same issue. thanks!
