### ISSUE TITLE
Add dates to evtx metrics

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#77]
First and last record date would be useful

**Comment by EricZimmerman** [comment]
hows this

![image](https://user-images.githubusercontent.com/4265254/58501494-921a2880-8152-11e9-9133-50538a55eed8.png)

**Comment by randomaccess3** [comment]
Looks great! 

Definitely would help to be able to dump this all into a file after processing

**Comment by EricZimmerman** [comment]
ok ill push an update.

the best way to get all that in a file is redirect to a file, or in KAPE, use --debug

in KAPE you could always cheat and use the ExportFile option to capture stdout too =)
