### ISSUE TITLE
TLE

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#78]
Automatically or right click option to pretty print json data when you expand a field

**Comment by EricZimmerman** [comment]
hows this

![image](https://user-images.githubusercontent.com/4265254/59201695-fb456700-8b68-11e9-9dd2-91b5765256ee.png)

**Comment by EricZimmerman** [comment]
it wont be in the main view. you have to double click a cell to view the contents, then you can Format

**Comment by EricZimmerman** [comment]
done in 0.9.2.1
