### ISSUE TITLE
Extecmd: Warn on misordered events

### ISSUE THREAD

**Issue by randomaccess3** [EricZimmerman/Issues#79]
Event logs should be written sequentially and the timestamps should increment accordingly (within a short variance, probably 60 seconds)

It would be great to highlight if the record numbers increment but the timestamps are out of order

**Comment by EricZimmerman** [comment]
if you can find an actual example log file with this in it, i will look, else, sort and compare as needed

**Comment by EricZimmerman** [comment]
done
