### ISSUE TITLE
RegistryExplorer: Deleted user showing in SAM 'Users' table, but no indication user is deleted.

### ISSUE THREAD

**Issue by Fetchered** [EricZimmerman/Issues#81]
The SAM Users table is an extremely helpful feature, but I noticed that when a deleted record is 'recovered', the user shows up in the Users table, but there is no indication here that the user is a deleted user.  It would be great to see a field here showing that the user is a deleted user, or that the information comes from a deleted, recovered key.

Perhaps another column called 'Is deleted' or 'Recovered' would provide that info.

Using latest 1.4.3 (occurs in 1.4.2 as well).

Sample SAM attached (data is from a testing environment, had to add TXT extension for Github to accept).
[SAM.txt](https://github.com/EricZimmerman/Issues/files/3293517/SAM.txt)

**Comment by EricZimmerman** [comment]
this is a function of the plugin vs looking at the data itself. the data itself should always be cross referenced. if someone wants to update the open source plugin to add this, great, else, its good i think

https://github.com/EricZimmerman/RegistryPlugins/tree/master/RegistryPlugin.SAM
