### ISSUE TITLE
RegistryExplorer: Add ability to extract UserTile without manual parsing.

### ISSUE THREAD

**Issue by Fetchered** [EricZimmerman/Issues#82]
UserTile can be a useful piece of info depending on the nature of an investigation. While it is possible to parse out the UserTile manually (read header at correct offset, count bytes, copy-paste etc), it would be helpful if RegistryExplorer could allow you to recover it with a more user-friendly method.

**Comment by EricZimmerman** [comment]
do you have any documentation on this? what do you expect RE  to do here?

**Comment by Fetchered** [comment]
The UserTile value in the SAM -> Domains -> Account -> Users -> RID stores the users tile photo they choose to represent a profile picture, as a BMP formatted image. The file header starts at decimal offset 16 in the key with the values of ’42 4D’ (BM) with the first two bytes, then the next 4 bytes are the size of the file in bytes. Selecting all bytes from the 42 4D to a total of the 4-byte file size, then converting that hex and saving the image with the filename found at the end of the UserTile key will give you a tile-sized image of the photo used as the persons profile picture.

 

The SAM hive I sent you earlier has a few examples of this in there to experiment with if you wish. I guess one suggestion for what RE could do here is to read that data, and have the words ‘UserTile’ be a clickable link to allow the user to download an extracted copy of the photo with the filename found in the UserTile key by default. 

 

There are a few references to this in various locations, the links for which I’ll provide below, but I haven’t found any specific instructions on it. I’ve had to figure it out manually.

Both of these are by Josh Brunty, I’m still looking for a good Microsoft reference.

 

https://www.forensicfocus.com/c/mode=prnt/id=49/webinars/2012/windows-8-forensics---a-first-look/

https://prezi.com/hdvnmojrf3pb/windows-8-forensics-techno-security-2012/

**Comment by EricZimmerman** [comment]
![image](https://user-images.githubusercontent.com/4265254/60760963-f3180480-a00c-11e9-903f-fac18bcc1a49.png)

your suggested idea, while nice, is super super specific to a sam hive and only in certain cases then. ill see what i can do to make this easier. i just exported the value and then renamed the file after stripping out the header

**Comment by EricZimmerman** [comment]
this is all you need to do apparently, right click  the value, export value as binary, open in hex editor, and strip out the first 16 bytes. the tail end of the file does not matter.

**Comment by EricZimmerman** [comment]
ok, so in 1.5, i added the ability to export the selected bytes from the hex viewer.

you can also double click on the Bytes selected status box and enter the number of bytes to highlight.

![image](https://user-images.githubusercontent.com/4265254/60761069-60c53000-a00f-11e9-91c7-5683b2ce34dd.png)

this is the best way to do this in 1.5
