### ISSUE TITLE
RegistryExplorer: Add 'Save As' feature to Projects

### ISSUE THREAD

**Issue by Fetchered** [EricZimmerman/Issues#83]
I use RegistryExplorer on a regular basis not just for investigation, but for instruction as well. During a recent lesson, I had a student load several hives, save the project, and continue to work in it. We moved on to a new lesson, they unloaded all hives, and loaded several new ones. 
When it came time to close RegistryExplorer, they realized their mistake when they went to save their project, but if they were to do so it would overwrite the project they just made. 

A 'Save As' feature for the Projects would definitely be useful, not just in an instructional environment, but also when we analysts also accidentally do the same thing.

**Comment by EricZimmerman** [comment]
Done in 1.5
