### ISSUE TITLE
variable %computername% not working with _kape.cli

### ISSUE THREAD

**Issue by hanzelmannes** [EricZimmerman/Issues#85]
When I use the environment variable %COMPUTERNAME%  as –tdest folder, all goes well in the case I run Kape from a command line.

However when is use the same –tdest in a _kape.cli file, it won’t work. The destination folder name will then be “%COMPUTERNAME%” in stead of the computernname Kape is running on.

As an example:   My computername = DT032

command line:  kape --tsource c: --tdest .\%COMPUTERNAME%--%d\ --target SRUM --gui 
Works fine. The destination folder is created as a sub folder and is named DT032--20190620T140649  

The same command within a '_kape.cli' file,  (--tsource c: --tdest .\%COMPUTERNAME%--%d\ --target SRUM --gui) . Results in a folder named:  '%COMPUTERNAME%--20190620T141225'

Regards
Hans

**Comment by EricZimmerman** [comment]
This will be addressed this week, in KAPE 0.8.5.0, which adds %m variable that will be expanded to the Machine name where KAPE is running.
