### ISSUE TITLE
EZViewer: typo in extensions.yaml

### ISSUE THREAD

**Issue by Banaanhangwagen** [EricZimmerman/Issues#92]
There is a typo in the `extensions.yaml`, resulting in displaying png files in hex   ;)

![image](https://user-images.githubusercontent.com/25983612/62276934-69115f00-b445-11e9-9923-a0aee01d9983.png)

**Comment by EricZimmerman** [comment]
this is fixed. good find

**Comment by EricZimmerman** [comment]
if you check for updates ezviewer will update itself with the fix
