### ISSUE TITLE
KAPE sftp mode

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/Issues#95]
I'm running into an issue using the SFTP mode in KAPE. KAPE will start to transfer the data, but after some time, I get the following error in the console.

Message type 93 is not valid in the current context.

The console log also says that it cleans up the files afterwards, but they are still there.

**Comment by EricZimmerman** [comment]
Please send me the  logs and the steps to reproduce and I'll see. Is this 0871?

**Comment by Beercow** [comment]
Yes. This is 0871. Where would you like me to send the logs?

**Comment by EricZimmerman** [comment]
Zip and email em to my Gmail works

**Comment by Beercow** [comment]
I sent them to the kroll email.

**Comment by EricZimmerman** [comment]
look at your command line

Command line: --tsource C --target !All --tflush --tdest c:\temp\tout --zip %computername --scp 22 --scu brian --scpw XXXXXXXXX --scs 10.80.171.222 

you are missing the closing % on computername

you should also be using %m for this, and not an environment var, as it works with cmd and powershell that way

Variables: %d = Timestamp (yyyyMMddTHHmmss)
                   %m = Machine name


Try that and let me know if the issue persists.

**Comment by EricZimmerman** [comment]
93 appears to do with a window adjust:

https://github.com/sshnet/SSH.NET/blob/7691cb0b55f5e0de8dc2ad48dd824419471ab710/src/Renci.SshNet/Messages/Connection/ChannelWindowAdjustMessage.cs

i have swapped out the sftp client with the same vendor code i use for sftp server. testing it now, so this should help too

**Comment by EricZimmerman** [comment]
this is working WAY better. will have a build for you to test tomorrow. does that work?

**Comment by EricZimmerman** [comment]
twitter DMed you a link for test version

**Comment by Beercow** [comment]
That will work. Thank you for your time. I don’t think the % has anything to do with it though. It only seems to do it on larger collections. Small ones work just fine.

**Comment by EricZimmerman** [comment]
i tested basiccollection looped 3 times, which is like 899 MB transfer

no issues

**Comment by EricZimmerman** [comment]
ill release 0.8.7.2 tomorrow unless you find any issues.

**Comment by Beercow** [comment]
I think we are good. I have one more Scooby Doo mystery to solve, but I think it is on my end and nothing to do with KAPE.

**Comment by EricZimmerman** [comment]
Ok geeat
