### ISSUE TITLE
RegistryExplorer: Unable to load SYSTEM hive

### ISSUE THREAD

**Issue by kezzier** [EricZimmerman/Issues#96]
I am using v1.5.1.0. I am unable to load the SYSTEM hive and get the following error:
```
Sequence contains more than one matching element, Error message: Sequence contains more than one matching element, Stack trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Registry.RegistryHive.ParseHive()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RegistryExplorer.Forms.Main.<LoadHive>d__46.MoveNext()
```

**Comment by EricZimmerman** [comment]
I'd need the hives and transaction logs to look at this. Did it tell you the hive was dirty or no?

How did you extract the hive and log files?

**Comment by kezzier** [comment]
1) I sent you a mail with the hive and logs.
2) No.
3) I extracted them with X-WAYS.

**Comment by EricZimmerman** [comment]
Ok we'll just for kicks, mount the e01 with arsenal image mounter, and extract the hives with kape. I've seen xways mess up extraction recently. What version of xways is it?

**Comment by kezzier** [comment]
I have mounted it with arsenal image mounter and then extracted the hives with kape but still get the same error.
I use xways version 19.8 SR7

**Comment by EricZimmerman** [comment]
Ok. It's down to either a bug or a corruption issue. I'll look.
