### ISSUE TITLE
RegistryExplorer - USBSTOR Properties Displaying Local Time

### ISSUE THREAD

**Issue by Fetchered** [EricZimmerman/Issues#97]
RegistryExplorer 1.5.0.1
Windows 10 Enterprise 1607 LTSB
16GB RAM - x64 CPU

When viewing the SYSTEM\ControlSet001\Enum\USBSTOR\<device>\<serial>\Properties\{83da6326-97a6-4088-9453-a1923f573b29}\0066 and 0067 from a Windows 10 Pro 1709 System Hive, the 'Data' field on the right displays the timestamp in 'Local' time, not in UTC or the timezone of the System Hive.

I'm attaching a couple of screenshots of the issue. 
![0066](https://user-images.githubusercontent.com/10457978/65151627-746c1a00-d9f4-11e9-9e60-575de99dfe03.PNG)
![USB-Timestamp](https://user-images.githubusercontent.com/10457978/65151694-9b2a5080-d9f4-11e9-9ece-022501222e69.PNG)

I can provide the hive if required. Hive we are using comes from a test environment and may contain material not appropriate for public consumption.

Should clarify - the time displayed is not identified in a specific timezone OR identified as being in LOCAL. Recommend column list displayed timezone or timestamp be updated for UTC.

**Comment by EricZimmerman** [comment]
please send me a link to the hive or email it to my gmail address. ill fix this today

**Comment by EricZimmerman** [comment]
this is fixed. Check for updates with the powershell script and it will be right
![image](https://user-images.githubusercontent.com/4265254/65158995-653f9900-da01-11e9-9863-8366f527292f.png)
