### ISSUE TITLE
[Timeline explorer v0.9.3.0] Line-feed character misinterpreted in event details

### ISSUE THREAD

**Issue by bl4ckh0l3z** [EricZimmerman/Issues#99]
Timeline Explorer v0.9.3.0 parses the "\n" as a line feed char in an event detail.

The same issues was already identified in the past and closed as fixed in v0.9.2.0 (ref. https://github.com/EricZimmerman/Issues/issues/70).

![evidence](https://user-images.githubusercontent.com/8762278/65311751-e607ad80-db45-11e9-8a3c-cf584bb663cd.png)

**Comment by EricZimmerman** [comment]
Update to latest. It's been fixed for a while.

**Comment by EricZimmerman** [comment]
Oops I hit the wrong button. Try it with the latest version if it still doesn't work please send me a test file

**Comment by bl4ckh0l3z** [comment]
Tested with the latest version 0.9.3.0, downloaded from https://ericzimmerman.github.io

**Comment by EricZimmerman** [comment]
Okay send me a sample file and I'll take a look

**Comment by bl4ckh0l3z** [comment]
My pleasure...thanks for your time! 

[timeline2.txt](https://github.com/EricZimmerman/Issues/files/3635829/timeline2.txt)

**Comment by EricZimmerman** [comment]
what v ersion of L2t generated this? looks like an older version, because more current versions use XML for the long description vs plain text.

**Comment by EricZimmerman** [comment]
pushing update now that should do it, but, at least in FOR508

![image](https://user-images.githubusercontent.com/4265254/65337523-52120200-db96-11e9-8538-99fa556723cb.png)

![image](https://user-images.githubusercontent.com/4265254/65337532-563e1f80-db96-11e9-9e2b-331e1e356f9a.png)

**Comment by EricZimmerman** [comment]
please take a look and close if its resolved

**Comment by bl4ckh0l3z** [comment]
it works like a charm...! Thanks man
